A-lass/Algorithm-Study

kjhonggg95/baekjoon/30023.cpp, kjhonggg95/boj_template.cpp
[30023번: 전구 상태 바꾸기](https://www.acmicpc.net/problem/30023)
[이 문제](https://www.acmicpc.net/problem/2138) 와 유사함
세가지 경우의 수를 따져볼 수 있다.
첫 번째 연속한 전구들(1~3)의 상태를
1) 그대로 두기
2) 한 번 바꾸기
3) 두 번 바꾸기
이후 _i_ 번 전구의 색을 _i - 1_ 번째 색과 맞춰나간다. _( 1 < i < n - 2 )_
--> _i_ 번 전구의 색이 _i - 1_ 번 전구의 색과 다른데 지나친다면 모든 전구의 색이 같을 수 없다.
위 과정이 끝나고 모든 전구의 색이 일치한다면 변경의 최소값을 갱신한다.
```
int n, mn = 1e9;
string s;
void func(int cnt, vector<int> v)
{
for(int i = 0;i<3;i++)
v[i] = (v[i] + cnt) % 3;
for(int i = 1;i<n-2;i++)
{
if((v[i-1] == 0 && v[i] == 1)
|| (v[i-1] == 1 && v[i] == 2)
|| (v[i-1] == 2 && v[i] == 0))
{
for(int j = …
```
=> [kjhonggg95] 2023. 10. 31

dydwo0740/baekjoon/30023.java
https://www.acmicpc.net/problem/30023
입력 받은 문자열을 각각의 문자를 번호로 변환을 한뒤 int 배열에 저장을 했습니다.
그리고 맨앞 index의 숫자를 0번, 1번, 2번 변환을 하는 경우에 따라 i번째 색과 i-1번째 색을 같게 만드는 방법으로 진행을 했습니다.
그렇게 만들어진 배열이 모두 다 같은 경우가 나왔을때 답을 계속해서 초기화 하는 방식으로 해결했습니다.
이 문제에서 어려웠던 접근법은 맨앞 index의 숫자를 변환한 3가지 경우를 고려하는 것이였습니다. 초기의 생각은
맨앞 숫자는 고정한체 후순위의 값들을 그 앞의 숫자로 바꾸는 방법을 택했기에 정답이 나올 수 없었습니다.
```
int[] seq = new int[N]; …
```
=> [dydwo0740] 2023. 10. 31

ddingmin/baekjoon/30023.py, ddingmin/test.py
[LINK](https://www.acmicpc.net/problem/30023)
전구를 시작 색의 경우의 수는 3가지이다.
0122의 전구가 존재한다면
```
1. 012
2. 120
3. 201
```
다음의 경우의 수를 시작으로 0번째 전구와 동일하도록 끝까지 전구의 상태를 변경하여, 조건에 맞는다면 최솟값을 갱신해나간다.
```
import sys
arr = list(input().strip())
change = {'R': 'G', 'G': 'B', 'B': 'R'}
def change_light(idx, arr):
arr[idx], arr[idx + 1], arr[idx + 2] = change[arr[idx]], change[arr[idx + 1]], change[arr[idx + 2]]
return arr
def solve(new_arr):
count = 0
for i in range(1, n - 2):
while new_arr[0] != new_arr[i]:
count += 1
new_arr = change_light(i, new_arr)
if new_arr[0] == new_arr[-1] == new_arr[-2]:
return count
return float('inf')
answer = float('inf')
for i in range(3):
answer = min(answer, solve(arr.copy()) + i)
arr = change_light(0, arr)
if answer == …
```
=> [ddingmin] 2023. 10. 31

ajsthfldu/baekjoon/30023.py
https://www.acmicpc.net/problem/30023
i번째 요소를 i - 1번째 요소의 색상과 동일하게 맞춰나가는 그리디 알고리즘 문제
0번째 요소에 대해서 3가지 색상에 대해 모두 시도해보고 정답구하기
```
import sys
def solve():
if n == 1:
return 0
if n == 2:
if color[0] == color[1]:
return 0
return -1
if n == 3:
if color[0] == color[1] and color[0] == color[2]:
return 0
else:
return -1
cnt = [0, 0, 0]
color1 = color.copy()
cnt[0] = change_light(color1, 0)
color2 = color.copy()
ch(color2, 0, 1)
cnt[1] = change_light(color2, 1)
color3 = color.copy()
ch(color3, 0, 2)
cnt[2] = change_light(color3, 2)
cnt = [x for x in cnt if x != -1]
return min(cnt)
def change_light(color, init):
ans = init
before = color[0]
for i in range(1, n - 2):
if color[i] == before:
continue
diff = 1 if (color[i] + 1) % 3 == before else 2
ans += diff
ch(color, i, diff)
if color[-1] != color[-2] …
```
=> [ajsthfldu] 2023. 11. 01

kjhonggg95/baekjoon/11607.cpp
[11607번: Grid](https://www.acmicpc.net/problem/11607)
현재 위치에서 이동할 수 있는 다음 위치의 좌표를 계산해나가면서 _(n - 1, m - 1)_ 까지 이동한다.
한 번 이동할 때마다 _cnt_ 를 증가시키면서 _(n - 1, m - 1)_ 에 도달했을 때 _cnt_ 를 출력한다.
모든 탐색이 끝났는데도 _(n - 1,m - 1)_ 에 도달하지 못한다면 갈 수 없는 경우이므로 _"IMPOSSIBLE"_ 을 출력한다
```
int dx[4] = {1,0,-1,0};
int dy[4] = {0,1,0,-1};
char arr[501][501];
bool vis[501][501];
int main()
{
fastio;
int n, m;
cin >> n >> m;
for(int i = 0;i<n;i++)
for(int j = 0;j<m;j++)
cin >> arr[i][j];
queue<pair<pii, int>> q;
q.push({{0,0}, 0});
vis[0][0] = true;
while(!q.empty())
{
auto cur = q.front().X;
auto cnt = q.front().Y;
q.pop(); …
```
=> [kjhonggg95] 2023. 11. 01

dydwo0740/baekjoon/11607.java
https://www.acmicpc.net/problem/11607
bfs를 이용하여 최단거리를 탐색했습니다. 기존에 한방햠만 가던 문제에서 board에 저장된 숫자를 곱하여 추가적으로
더 멀리 갈수 있도록 하는 것이 문제의 핵심입니다.
```
static int N;
static int M;
M = Integer.parseInt(st.nextToken());
int[][] board = new int[N][M];
for(int i=0;i<N;i++){
String str = st.nextToken();
for(int j=0;j<M;j++){
board[i][j] = …
```
=> [dydwo0740] 2023. 11. 02

ajsthfldu/baekjoon/11607.py
https://www.acmicpc.net/problem/11607
dfs/bfs를 사용하여 최단거리 구하기
```
import sys
def bfs(graph, ix, iy):
queue = deque([(ix, iy, 0)])
visited[ix][iy] = True
while queue:
cx, cy, step = queue.popleft()
jump = graph[cx][cy]
nx = cx + dx[i] * jump
ny = cy + dy[i] * jump
if not (0 <= nx < n and 0 <= ny < m):
continue
if visited[nx][ny]:
continue
if nx == n - 1 and ny == m - 1:
return step + 1
queue.append((nx, ny, step + 1))
visited[nx][ny] = True
return -1
n, m = map(int, sys.stdin.readline().split())
graph = [list(map(int, sys.stdin.readline().strip())) for _ in range(n)]
visited = [[False] * m for _ in range(n)]
dx = [0, 0, 1, -1]
dy = [1, -1, 0, 0]
x = bfs(graph, 0, 0)
print(x if x != -1 else 'IMPOSSIBLE')
```
=> [ajsthfldu] 2023. 11. 02

ddingmin/baekjoon/11607.py
https://www.acmicpc.net/problem/11607
BFS 문제이다.
시작지점부터 4방향으로 BFS를 돌려주되, 방문체크와 더불어 최단 점프를 체크해야한다.
> 방문 체크 배열을 `float('inf')`값으로 해결하면 더 간견할게 코드를 작성할 수 있을 것 같다.
```
import sys
dx, dy = [1, -1, 0, 0], [0, 0, 1, -1]
n, m = map(int, input().split())
arr = [list(map(int, list(input().strip()))) for _ in range(n)]
visit = [[0] * m for _ in range(n)]
q = deque()
q.append([0, 0])
visit[0][0] = 1
while q:
i, j = q.popleft()
x, y = i + dx[k] * arr[i][j], j + dy[k] * arr[i][j]
if not(0 <= x < n and 0 <= y < m):
continue
if visit[x][y] == 0:
q.append([x, y])
visit[x][y] = visit[i][j] + 1
elif visit[x][y] > visit[i][j] + 1:
q.append([x, y])
visit[x][y] = visit[i][j] + 1
if visit[-1][-1] == 0:
print("IMPOSSIBLE")
else: …
```
=> [ddingmin] 2023. 11. 01

ddingmin/baekjoon/14497.py
https://www.acmicpc.net/problem/14497
> 알고리즘: BFS
주난이의 위치를 시작으로 BFS를 탐색한다.
1. 최종 방문 배열을 통해 이전 턴에 움직였던 칸들을 체크한다.
2. BFS를 돌면서 `[최종 방문 배열]`, `[방문 X + 빈 공간]` 이라면 이동한다.
3. 마주치는 장애물들은 `delete` 배열에 담고 큐에는 더이상 추가하지 않는다.
4. 큐가 비게되면 delete 배열을 순회하면서 최종 방문배열 체크와 실제 장애물을 제거한다.
위 `jump()`로직을 목표 위치가 제거될 때 까지 반복한다.
``` python
import sys
dx, dy = [1, -1, 0, 0], [0, 0, 1, -1]
n, m = map(int, input().split())
r, c, rr, cc = map(int, input().split())
r, c, rr, cc = r - 1, c - 1, rr - 1, cc - 1
arr = [list(input().strip()) for _ in range(n)]
visited = [[0] * m for _ in range(n)]
def jump():
q = deque()
visit = [[0] * m for _ in range(n)]
visit[r][c] = 1
q.append([r, c])
delete = []
while q:
i, j = q.popleft()
x, y = i + dx[k], j + …
```
=> [ddingmin] 2023. 11. 02

kjhonggg95/baekjoon/25319.cpp
[25319번: Twitch Plays VIIIbit Explorer](https://www.acmicpc.net/problem/25319
)
1. 맵을 입력받으면서 각 알파벳이 나온 빈도수를 `freq` 배열에 저장한다
2. 아이디를 반복시키면서 맵에 있는 알파벳들로 아이디를 몇 번 강화할 수 있는지 구한다(`mx_c`)
3. 시작지점, 도착지점, 최대 강화 회수에 따라 방문 순서에 예외가 있는지 확인하고 고쳐준다.
4. 방문 순서대로 탐색하면서 명령어를 갱신해나간다.
``` c++
int dx[4] = {1, 0, -1, 0};
int dy[4] = {0, 1, 0, -1};
int n, m, l, mx_c;
string s;
char arr[51][51];
int freq[26];
bool vis[51][51];
vector<pii> seq; // 방문 순서
// (1, 1) -> (n, m)
// 아이디 S 가 최대 몇 번 나올 수 있는지 구한다
int getMaxC()
{
int cnt = 0;
bool flag = true;
while (flag)
{
for (auto e : s)
{
if (freq[e - 'a'] > 0)
{
freq[e - …
```
=> [kjhonggg95] 2023. 11. 03

ddingmin/baekjoon/25319.py
[25319: Twitch Plays VIIIbit Explorer](https://www.acmicpc.net/problem/25319)
레벨업을 할 수 있는 값을 찾기 위해 맵에 존재하는 알파벳들의 개수에 이름의 존재하는 알파벳의 개수를 각각 나누어 최솟값으로 구해준다.
출발 좌표와 도착 좌표를 통해 명령어를 생성하는 함수를 만들어준다.
``` python
def get_cmd(i, j, x, y):
result = ""
if i > x:
result += "U" * (i - x)
else:
result += "D" * (x - i)
if j > y:
result += "L" * (j - y)
else:
result += "R" * (y - j)
return result + "P"
```
**백트래킹**
1. 당장 필요한 알파벳에 대한 좌표로 이동하며 단어를 주울 때 마다 방문 체크를 한다.
2. 이동할 때 명령어 `get_cmd()`를 붙여준다.
3. 인덱스를 통해 다음 먹을 알파벳을 계산하며, `mod`한 값이 0일 경우 레벨업 시킨다.
4. 목표하는 레벨업에 도달하면 도착 지점까지 명령어를 `get_cmd()`를 통해 구해주지만 마지막 P 명령어는 제거해 붙여준다.
``` python
import sys
sys.setrecursionlimit(10 ** 5)
n, m, r = map(int, input().split())
alphabets = {}
arr = [list(input().strip()) for _ in range(n)]
for i in …
```
=> [ddingmin] 2023. 11. 03

dydwo0740/baekjoon/25319.java
https://www.acmicpc.net/problem/25319
우선 처음에는 순열을 활용하여 탐색을 진행했기에 시간초과가 발생을 했습니다.
그래서 Map 을 활용하여 레벨업 할 수 있는 경우의 수를 구하고
bfs를 활용하여 이동할 수 있는 경우의 수를 문자열로 뽑아내었습니다.
``` java
static int N;
static int M;
static int S;
static String id;
static int[] row = {-1, 1, 0, 0};
static int[] col = {0, 0, -1, 1};
static char[] alpha = {'U', 'D', 'L', 'R'};
static class Location {
int x;
int y;
String move;
public Location(int x, int y) {
this.x = x;
this.y = y;
}
public Location(int x, int y, String move) {
this.x = x;
this.y = y;
this.move = move;
}
}
static int ans = Integer.MAX_VALUE;
static Map<Character, List<Location>> info = new HashMap<>();
BufferedReader br = …
```
=> [dydwo0740] 2023. 11. 03 

dydwo0740/baekjoon/25170.java
https://www.acmicpc.net/problem/25710
시간복잡도를 줄이기 위해서 생각이 필요한 문제였습니다. 해당 문제의 핵심은 2개 이상 count를 가진 숫자에 대해서는 2번만 넣어주는 것입니다. 이 아이디어를 떠올리지 못해 고비를 겪었습니다.
``` java
static int N;
static int ans = Integer.MIN_VALUE;
Map<Integer, Integer> map = new HashMap<>();
for(int i=0;i<N;i++){
int idx = Integer.parseInt(st.nextToken());
if(map.containsKey(idx)){
if(map.get(idx) == 2){ …
```
=> [dydwo0740] 2023. 11. 04 

ajsthfldu/baekjoon/25319.py
https://www.acmicpc.net/problem/25319
도착 시 소지 아이템이 없어야 된다는 조건에 주의
``` python
import sys
def find_item(dungeon, c):
for i in range(n):
for j in range(m):
if dungeon[i][j] == c:
dungeon[i][j] = '0'
return i, j
return -1, -1
def solve():
c = 0
x = 0
y = 0
tx = 0
ty = 0
while True:
for ch in s:
nx, ny = find_item(dungeon, ch)
if nx == -1 and ny == -1:
tmp.clear()
move_route(n - 1, m - 1, x, y)
ans.extend(tmp)
return c
move_route(nx, ny, tx, ty)
tx, ty = nx, ny
tmp.append('P')
ans.extend(tmp)
x, y = tx, ty
tmp.clear()
c += 1
def move_route(nx, ny, x, y):
dx = nx - x
dy = ny - y
if dx > 0:
tmp.extend('D' * dx)
elif dx < 0:
tmp.extend('U' * -dx)
if dy > 0:
tmp.extend('R' * dy)
elif dy < 0:
tmp.extend('L' * -dy)
n, m, len_s = map(int, sys.stdin.readline().split()) …
```
=> [ajsthfldu] 2023. 11. 03

dydwo0740/baekjoon/4920.java
https://www.acmicpc.net/problem/4920
해당 문제를 해결할때 테스트 케이스와 최댓값 사이에 .을 찍지 않아서 오류가 발생했습니다.
문제 해결에는 도형을 90도 돌려가면서 최댓값을 계속해서 초기화 하는 방식으로 해결했습니다.
다른 분들의 풀이를 보니 미리 배열에 초기화를 하고 했는데 저는 증감이 되는 수를 적어놓고
90도 회전을 할때는 x와 y값을 적절히 바꿔주면서 해결했습니다.
y좌표는 이전의 -x좌표가 되고 x좌표는 이전의 y가 됩니다. -> 해당 규칙은 한번 다시 생각해봐야겠습니다.
``` java
static int[][] row = {{0, 0, 0}, {0, 1, 0}, {0, 0, 1}, {0, 0, 1}, {0, 1, 0}};
static int[][] col = {{1, 1, 1}, {1, 0, 1}, {1, 1, 0}, {1, 1, -1}, {1, 0, -1}};
static int[][] board;
static int N;
static int max;
static int test = 1;
BufferedWriter bw = new BufferedWriter(new …
```
=> [dydwo0740] 2023. 11. 05

kjhonggg95/baekjoon/4920.cpp
[4920번: 테트리스 게임](https://www.acmicpc.net/problem/4920)
[14500번: 테트로미노](https://www.acmicpc.net/problem/14500)와 거의 동일한 문제다.
5가지 조각을 회전시켜서 얻을 수 있는 모든 경우에 대하여 계산한다.
각 조각마다 범위 값을 잘 체크해주어야 하며 표의 값이 음수가 들어올 수 있음에 주의해야 한다.
``` c++
int arr[101][101];
int main()
{
fastio;
int n;
for (int t = 1;;t++)
{
cin >> n;
if (n == 0)
return 0;
memset(arr, 0, sizeof(arr));
int mx = -1e9;
for (int i = 0; i < n; i++)
for (int j = 0; j < n; j++)
cin >> arr[i][j];
// ■ ■ ■ ■
for (int i = 0; i < n; i++)
for (int j = 0; j < n - 3; j++)
mx = max(mx, arr[i][j] + arr[i][j + 1] + arr[i][j + 2] + arr[i][j + 3]);
// ■
// ■
// ■ …
```
=> [kjhonggg95] 2023. 11. 05

ddingmin/baekjoon/25710.py
https://www.acmicpc.net/problem/25710
배열의 크기는 10,000 이기 때문에 n^2의 이중 포문으로 문제를 해결할 수 없다.
하지만 주어지는 숫자의 범위가 1 <= a <= 999 이므로 중복된 수를 제거하여 계산한다면 시간 초과를 막을 수 있다.
단순히 `set`을 이용한다면 같은 수가 나오는 예외 케이스에 해결할 수 없으므로 이를 주의해서 해결하면 된다.
``` python
import sys
arr = list(map(int, input().split()))
def get_dict_numbers(arr):
result = {}
for num in arr:
if num not in result:
result[num] = 0
result[num] += 1
return result
def get_scores(num1, num2):
result = 0
for num in str(num1 * num2):
result += int(num)
return result
def solve(n, arr):
answer = 0
num_counter = get_dict_numbers(arr)
for num1 in num_counter.keys():
for num2 in num_counter.keys():
if num1 == num2 and num_counter[num1] == 1:
continue
answer = max(answer, get_scores(num1, num2))
return answer …
```
=> [ddingmin] 2023. 11. 05

ajsthfldu/baekjoon/25710.py
https://www.acmicpc.net/problem/25710
3번 이상 중복되는 요소 제거
``` python
import sys
def main():
a = list(map(int, sys.stdin.readline().split()))
cnt = [0] * 1000
b = []
for x in a:
if cnt[x] == 0 or cnt[x] == 1:
b.append(x)
cnt[x] += 1
selected = [False] * 1000
computed = [False] * (999 * 999 + 1)
max_score = 0
for i in range(len(b) - 1):
if selected[b[i]]:
continue
for j in range(i + 1, len(b)):
mul = b[i] * b[j]
if computed[mul]:
continue
score = sum(map(int, str(mul)))
max_score = max(max_score, score)
computed[mul] = True
selected[b[i]] = True
print(max_score)
main()
```
=> [ajsthfldu] 2023. 11. 04

ajsthfldu/baekjoon/4920.py
https://www.acmicpc.net/problem/4920
테트리스 블럭을 좌표화하고 그래프의 모든 칸에 대해 블럭을 적용한다.
``` python
import sys
tet = []
tet.append([(0, 0), (0, 1), (0, 2), (0, 3)])
tet.append([(0, 0), (1, 0), (2, 0), (3, 0)])
tet.append([(0, 0), (0, 1), (1, 1), (1, 2)])
tet.append([(0, 0), (1, 0), (1, -1), (2, -1)])
tet.append([(0, 0), (0, 1), (0, 2), (1, 2)]) # ㄱ
tet.append([(0, 0), (1, 0), (2, 0), (2, -1)]) #ㅢ
tet.append([(0, 0), (1, 0), (1, 1), (1, 2)]) # ㄴ
tet.append([(0, 0), (0, 1), (1, 0), (2, 0)])
tet.append([(0, 0), (0, 1), (0, 2), (1, 1)]) # ㅜ
tet.append([(0, 0), (1, 0), (2, 0), (1, -1)]) # # ㅓ
tet.append([(0, 0), (1, 0), (1, -1), (1, 1)]) # ㅗ
tet.append([(0, 0), (1, 0), (2, 0), (1, 1)]) # ㅏ
tet.append([(0, 0), (0, 1), (1, 0), (1, 1)])
k = 1
while True:
n = …
```
=> [ajsthfldu] 2023. 11. 05

dydwo0740/baekjoon/19845.java
https://www.acmicpc.net/problem/19845
중력이 작용을 한다는 것이 상당한 힌트였습니다. 앞으로 문제를 꼼꼼이 읽어야겠습니다.
가로 방향으로는 좌표 값으로 판단을 할 수 있고, 세로 방향으로는 LowerBound를 통해 계산을 했습니다.
``` java
static int[] count;
int Q = Integer.parseInt(st.nextToken());
int[] seq = new int[N + 1];
count = new int[N + 1];
for(int i=1;i<=N;i++){
seq[i] = Integer.parseInt(st.nextToken());
count[i] = seq[i];
} …
```
=> [dydwo0740] 2023. 11. 06

ajsthfldu/baekjoon/19845.py
https://www.acmicpc.net/problem/19845
높이를 구할 때 이진탐색을 통해 빠르게 구한다. 찾는 값 중 가장 인덱스가 큰 것은 end를 고르면 된다.
``` python
import sys
def main():
n, q = map(int, sys.stdin.readline().split())
ans = []
a = [0] + list(map(int, sys.stdin.readline().split()))
for i in range(q):
x, y = map(int, sys.stdin.readline().split())
if x > a[y]:
ans.append('0')
continue
cnt = 1
cnt += a[y] - x
start = y
end = n
while start <= end:
mid = (start + end) // 2
if a[mid] < x:
end = mid - 1
else:
start = mid + 1
cnt += end - y
ans.append(str(cnt))
print('\n'.join(ans))
main()
```
=> [ajsthfldu] 2023. 11. 06

kjhonggg95/baekjoon/15809.cpp, kjhonggg95/baekjoon/19845.cpp
[15809번: 전국시대](https://www.acmicpc.net/problem/15809)
동맹과 속국이 되는 로직을 `union-find`로 구현했다.
`union`을 하는 과정에서 동맹으로 인한 `union`과 전쟁 후 속국이 되는 `union`을 각각 따로 구현했다.
번호가 작은 나라가 번호가 큰 나라의 부모가 되도록 하였다.
이 때 자식이 되는 나라는 `live` 배열에서 false로 체크한다.
두 나라를 병사 수에 따라 `winner`/`loser` 로 구분하여 union 해준다. 진 나라의 부모가 이긴 나라가 되도록 한다.
이 때 전쟁에서 진 나라는 `live` 배열에서 false로 체크한다.
`1 ~ n` 까지의 나라 중 살아있는 나라(`live[i] == true`)의 병사 수를 `ans`에 저장한 뒤 정렬 후 사이즈와 함께 출력
``` c++
int n, m, a, o, p, q;
int par[100001];
int arr[100001];
bool live[100001];
// find
int find(int u)
{
if(par[u] < 0) return u;
return par[u] = find(par[u]);
}
// 동맹
void …
```
=> [kjhonggg95] 2023. 11. 07

kjhonggg95/baekjoon/15809.cpp, kjhonggg95/baekjoon/18188.cpp, kjhonggg95/baekjoon/19845.cpp
[15188번: 다오의 데이트](https://www.acmicpc.net/problem/18188)
백트래킹으로 매 스텝마다 이동 가능한 방향으로 이동하면서 방향 정보까지 인자로 넘겨준다.
디지니를 만나면 `ans`를 갱신해준다.
``` c++
int h, w, n;
char arr[21][21];
char dir[21][2];
pii st;
string s, ans = "NO";
void dfs(int curR, int curC, int step, string cmd)
{
if (step > n || curR <= 0 || curR > h || curC <= 0 || curC > w || arr[curR][curC] == '@')
return;
if (arr[curR][curC] == 'Z')
{
ans = "YES\n" + cmd;
return;
}
for (int i = 0; i < 2; i++)
{
if (dir[step][i] == 'W')
dfs(curR - 1, curC, step + 1, cmd + 'W');
else if (dir[step][i] == 'A')
dfs(curR, curC - 1, step + 1, cmd + 'A');
else …
```
=> [kjhonggg95] 2023. 11. 08

dydwo0740/baekjoon/15809.java
https://www.acmicpc.net/problem/15809
union-find 를 이용하여 문제를 해결하였습니다. 각 국가에 대해서 동맹을 맺거나 전쟁을 진행할때 union 양식을 
수정하여해결합니다.
``` java
static int[] parent;
static int[] amount;
static int N;
parent = new int[N + 1];
amount = new int[N + 1];
for (int i = 1; i <= N; i++) {
amount[i] = Integer.parseInt(st.nextToken());
parent[i] = i;
} …
```
=> [dydwo0740] 2023. 11. 07

ddingmin/baekjoon/18188.py, ddingmin/baekjoon/19845.py, ddingmin/baekjoon/25710.py
https://www.acmicpc.net/problem/18188
주어진 대로 BFS를 통해서 구현하면 되는 문제이다.
하지만 방문 체크를 한다면 반례가 발생해 통과하지 못하는 상황이 발생할 수 있다.
- 4방향으로 자유롭게 이동하는 형태가 아니라 턴에 맞게 주어진 방향으로 이동할 수 있기 때문에 방문 체크 없이 돌아야 한다.
- 종료 시점은 주어진 모든 턴을 소진한 경우 잡아준다면 시간 넉넉히 문제를 해결할 수 있다.
``` python
import sys
def main():
dir = {'W': [-1, 0], 'S': [1, 0], 'A': [0, -1], 'D': [0, 1]}
h, w = map(int, input().split())
arr = [list(input().strip()) for _ in range(h)]
for i in range(h):
for j in range(w):
if arr[i][j] == 'D':
arr[i][j] = '.'
sx, sy = i, j
move = [list(map(str, input().split())) for _ in range(n)]
def solve(sx, sy):
q = deque()
q.append([sx, sy, ""])
visit = [[0] * w for _ in range(h)]
visit[sx][sy] = 1
while q:
i, j, cmd = q.popleft()
if arr[i][j] == 'Z': …
```
=> [ddingmin] 2023. 11. 09

kjhonggg95/baekjoon/15809.cpp, kjhonggg95/baekjoon/18188.cpp, kjhonggg95/baekjoon/19845.cpp, kjhonggg95/baekjoon/27942.cpp
[27942번: :danceplant:](https://www.acmicpc.net/problem/27942)
`upR` : 윗 변
`downR` : 아랫 변
`leftC` : 왼쪽 변
`rightC` : 오른쪽 변
각 변들과 맞닿아 있는 부분의 양분 합(`sum`)을 구한다.
* 음수인 양분도 존재하며, 양분 합이 0 이하라면 더 이상 몸을 늘이지 않는다는 조건이 있으므로 최소 양분 합의 값을 `1`로 설정해둔다.
*  현재 가능한 많은 양분을 먹는 방향이 여러가지면 `상->하->좌->우` 순으로 먹으므로 탐색은 **역순**으로 하여 최대로 먹을 수 있는 방향을 갱신한다.
* 초기 방향은 `0`으로 설정해둔다. 양분을 먹을 수 있는 방향을 갱신하되, 탐색이 끝난 후에도 `0`이라면 먹을 수 있는 방향이 없다는 뜻이므로 탐색을 종료한다.
``` c++
#define R 1
#define L 2
#define D 3
#define U 4
int n, upR, downR, leftC, rightC, tot;
short arr[3001][3001];
char dirarr[5] = {' ', 'R', 'L', 'D', 'U'};
string cmd = "";
int …
```
=> [kjhonggg95] 2023. 11. 09

dydwo0740/baekjoon/18188.java
https://www.acmicpc.net/problem/18188
dfs를 이용하여 문제를 해결했습니다. 그리고 마리드의 방향을 고려해서 움직여야 합니다.
해당 문제의 핵심은 방문체크를 하지 않는 것입니다.
``` java
static int N;
static int M;
static int Q;
static int[][] board;
static int[][] quest;
static char[][] shape;
static int answer = Integer.MAX_VALUE;
static String ans = "";
M = Integer.parseInt(st.nextToken());
board = new …
```
=> [dydwo0740] 2023. 11. 08 

ajsthfldu/baekjoon/18188.py
https://www.acmicpc.net/problem/18188
그래프 탐색
``` python
import sys
def bfs(graph, x, y, n, movable, ans):
queue = deque([(x, y, 0, [])])
while queue:
cx, cy, step, path = queue.popleft()
for d in movable[step]:
dx, dy = dir[d]
nx = cx + dx
ny = cy + dy
if nx < 0 or nx >= h or ny < 0 or ny >= w:
continue
if graph[nx][ny] == '@':
continue
if graph[nx][ny] == 'Z':
ans.extend(path)
ans.append(d)
return True
if step + 1 == n:
continue
npath = path.copy()
npath.append(d)
queue.append((nx, ny, step + 1, npath))
return False
def main():
graph = [list(sys.stdin.readline().strip()) for _ in range(h)]
movable = [list(sys.stdin.readline().strip().split()) for _ in range(n)]
ans = []
x, y = 0, 0
for i in range(h):
for j in range(w):
if …
```
=> [ajsthfldu] 2023. 11. 08

dydwo0740/baekjoon/27942.java
https://www.acmicpc.net/problem/27942
그냥 조건에 맞게 dfs를 돌리는 문제입니다.
그래서 조건에 맞게 dfs를 계속해서 돌린다음 max를 초기화 하는 단계를 거쳤습니다.
``` java
static int N;
static int[][] board;
static char[] alpha = {'L', 'R', 'U', 'D'};
static int answer = Integer.MIN_VALUE;
static String ans = "";
board = new int[N + 1][N + 1];
for (int i = 1; i <= N; i++) {
st = new …
```
=> [dydwo0740] 2023. 11. 09 

ajsthfldu/baekjoon/27942.py
https://www.acmicpc.net/problem/27942
상하좌우 시작점과 높이, 너비를 저장하고 확장된 방향에 따라 시작점과 높이, 너비를 업데이트하고 답을 구한다.
``` python
import sys
def main():
graph = [list(map(int, sys.stdin.readline().split())) for _ in range(n)]
h, w = 2, 2
total = 0
ans = []
init_point = {
'U': [n // 2 - 2, n // 2 - 1],
'D': [n // 2 + 1, n // 2 - 1],
'L': [n // 2 - 1, n // 2 - 2],
'R': [n // 2 - 1, n // 2 + 1]
}
while True:
max_score = 0
max_sym = ''
num_extensible = 4
for sym, (x, y) in init_point.items():
tmp_sum = 0
if x < 0 or x >= n or y < 0 or y >= n:
num_extensible -= 1
continue
if sym == 'U' or sym == 'D':
tmp_sum = sum(graph[x][y:y + w])
else:
for i in range(h):
tmp_sum += graph[x + i][y]
if tmp_sum <= 0:
num_extensible -= 1
continue
if tmp_sum > max_score:
max_sym = sym
max_score = …
```
=> [ajsthfldu] 2023. 11. 09

kjhonggg95/baekjoon/15809.cpp, kjhonggg95/baekjoon/18188.cpp, kjhonggg95/baekjoon/19845.cpp, kjhonggg95/baekjoon/20924.cpp, kjhonggg95/baekjoon/27942.cpp
[20924번: 트리의 기둥과 가지](https://www.acmicpc.net/problem/20924)
**기둥의 길이**와 **가지의 길이**를 각각 따로 계산해서 구해준다.
1. 루트 == 기가 (루트의 자식 노드 개수 > 1)
* 기둥의 길이는 0이 되며, 기가 노드(`gg`)를 루트 노드(`rr`)로 할당해준다.
2. 리프 == 기가
* 루트에서부터 탐색을 시작해 끝(리프)까지 갔을 때의 거리(`mxleaf`)가 기둥의 길이가 된다.
* 기가 노드(`gg`)에서부터 탐색을 하면서 리프 노드까지의 가장 긴 거리(`mxleaf`)를 갱신해준다.
``` c++
int n, a, b, d, rr, gg, mxleaf;
vector<pii> g[200001]; // {dest, dist};
bool vis[200001];
// 기둥 : root ~ giga
// 가지 : giga ~ leaf
void dfs(int cur, int dist)
{
mxleaf = max(mxleaf, dist);
if (gg == 0 && g[cur].size() >= 3)
{
gg = cur;
return;
}
for (auto nxt : g[cur])
{
if …
```
=> [kjhonggg95] 2023. 11. 10 - [BOJ] 20924: 트리의 기둥과 가지

dydwo0740/baekjoon/200924.java
https://www.acmicpc.net/problem/20924
우선 기가노드를 탐색을 합니다. 여기서 주의할 점은 기가노드가 없을 수 있다는 것입니다.(테스트 케이스 꼭 다 돌려보기)
만약 기가노드가 존재한다면, 기가노드에서 DFS를 활용하여 가지의 길이 최댓값을 초기화
그리고 높이의 최댓값을 초기화 합니다.
``` java
import java.util.Comparator;
int v;
int dist;
public Node(int v, int dist) {
this.v = v;
this.dist = dist;
}
}
static int N;
static int root;
static int ans = Integer.MIN_VALUE;
// 우선 기가 노드를 탐색하고 기가 노드에서 …
```
=> [dydwo0740] 2023. 11. 10

ddingmin/baekjoon/18188.py, ddingmin/baekjoon/19845.py, ddingmin/baekjoon/20924.py, ddingmin/baekjoon/25710.py
https://www.acmicpc.net/problem/20924
가지가 없는 경우, root가 가지가 되는 경우, root만 존재하는 경우 등등 다양한 예외 테스트 케이스들이 존재한다.
예외 테스트 케이스에 대해 다양하게 생각해보고 문제를 해결하면 된다.
> 가지를 판단하기 위해서 현재 노드로부터 뻗어나갈 수 있는 다음 노드가 2개 이상이라는 조건을 생각한다면 예외 없이 해결할 수 있다.
> [tip] root -> leaf의 거리에서 root -> giga의 거리를 빼주는 방식으로 구현한다면 더욱 쉽게 구현할 수 있다.
``` python
import sys
def main():
n, root = map(int, input().split())
answer = [None, 0]
adj = [[] for _ in range(n + 1)]
visit = [0] * (n + 1)
q = deque()
for _ in range(n - 1):
a, b, dist = map(int, input().split())
adj[a].append([dist, b])
adj[b].append([dist, a])
q.append([0, root])
visit[root] = 1
while q:
cur_dist, cur = q.popleft()
answer[1] = max(answer[1], cur_dist)
count = 0
for next_dist, next in adj[cur]:
if visit[next]:
continue …
```
=> [ddingmin] 2023. 11. 10

kjhonggg95/baekjoon/14618.cpp, kjhonggg95/baekjoon/15809.cpp, kjhonggg95/baekjoon/18188.cpp, kjhonggg95/baekjoon/19845.cpp, kjhonggg95/baekjoon/20924.cpp, kjhonggg95/baekjoon/27942.cpp
[14618번: 총깡 총깡](https://www.acmicpc.net/problem/14618)
* A형집과 B형집에 대한 정보를 `map`에 저장해둔다.
* _3 ≤ N ≤ 5,000, 3 ≤ M ≤ 20,000_ 이므로 다익스트라로 각 집들에 대한 최단 경로를 구해준다. _O(ElogE)_
* 구한 최단경로들을 탐색하면서 각 정점까지의 거리와 A형집인지 B형집인지를 갱신한다. 
이 때 A형 집까지의 최단 거리와 B형 집까지의 최단 거리가 같다면 A형집을 선택하도록 처리해줘야 한다.
```  c++
#define A 1
#define B 2
#define INF 1e9
int n, m, j, k, x, u, v, w;
int d[5005];
map<int, int> house;
vector<pii> adj[5005];
int main()
{
fastio;
cin >> n >> m >> j >> k;
fill(d, d + n + 1, INF);
// A형 집
for(int i = 0;i<k;i++)
{
cin >> x;
house[x] = A;
}
// B형 집
for(int i = 0;i<k;i++)
{
cin >> x;
house[x] = B;
} …
```
=> [kjhonggg95] 2023. 11. 11

ddingmin/baekjoon/14618.py, ddingmin/baekjoon/18188.py, ddingmin/baekjoon/19845.py, ddingmin/baekjoon/20924.py, ddingmin/baekjoon/25710.py
https://www.acmicpc.net/problem/14618
문제만 잘 읽으면 되는 최단 거리를 구하는 다익스트라 문제이다.
1. 주어진 시작 노드에서 다익스트라로 최단 거리를 구한다.
2. A형 노드들을 순회하며 최단 거리를 갱신한다.
3. B형 노드들을 순회하며 최단 거리를 갱신한다.
4. A,B형 모두 도달할 수 없는 경우 예외 처리를 하여 답을 출력한다.
> 답을 구하기 위해 최단 거리를 갱신할 때 A형 집을 먼저 갱신하면 A,B형 집 두 최단 거리가 모두 동일할 때 예외 처리를 추가적으로 구현하지 않아도 된다.
``` python
import sys
import heapq
def solve(adj, visit, a_type, b_type, start):
visit[start] = 0
hq = [[0, start]]
while hq:
dist, cur = heapq.heappop(hq)
if visit[cur] != dist:
continue
for next_dist, nxt in adj[cur]:
total_dist = dist + next_dist
if total_dist < visit[nxt]:
visit[nxt] = total_dist
heapq.heappush(hq, [total_dist, nxt])
answer = [None, float('inf')]
for node in a_type:
if visit[node] < answer[1]:
answer = ['A', visit[node]]
for node in b_type:
if visit[node] < answer[1]:
answer …
```
=> [ddingmin] 2023. 11. 11

ajsthfldu/baekjoon/20924.py
https://www.acmicpc.net/problem/20924
기둥이 없는 경우도 있음에 주의
``` python
import sys
sys.setrecursionlimit(10 ** 6)
def dfs(graph, v, length):
if len(graph[v]) == 1:
global max_branch_length
max_branch_length = max(max_branch_length, length)
return
for nv, e in graph[v]:
if visited[nv]:
continue
visited[nv] = True
dfs(graph, nv, length + e)
def graph_update():
for i in range(n - 1):
a, b, d = map(int, sys.stdin.readline().split())
graph[a].append([b, d])
graph[b].append([a, d])
n, r = map(int, sys.stdin.readline().split())
graph = [[] for _ in range(n + 1)]
visited = [False] * (n + 1)
graph_update()
pillar_length = 0
max_branch_length = 0
if len(graph[r]) == 1:
while not visited[r] and len(graph[r]) <= 2:
visited[r] = True
for v, e in graph[r]:
if visited[v]:
continue …
```
=> [ajsthfldu] 2023. 11. 10

kjhonggg95/baekjoon/14618.cpp, kjhonggg95/baekjoon/15809.cpp, kjhonggg95/baekjoon/18188.cpp, kjhonggg95/baekjoon/19845.cpp, kjhonggg95/baekjoon/20924.cpp, kjhonggg95/baekjoon/25391.cpp, kjhonggg95/baekjoon/27942.cpp
[25391:번 특별상](https://www.acmicpc.net/problem/25391)
1. 심판이 매긴 점수 순으로 K명을 뽑는다.
2. 심판이 뽑은 K명에 속하지 않은 인원들 중 주최자가 준 점수가 높은 순으로 M명을 뽑는다.
``` c++
int n, m, k, a, b, cnt;
ll ans;
int main()
{
fastio;
cin >> n >> m >> k;
vector<pair<pii, bool>> v;
for (int i = 0; i < n; i++)
{
cin >> a >> b;
v.push_back({{a, b}, false});
}
// 심판 점수 순 정렬
sort(v.begin(), v.end(), 
[](const pair<pii, bool> &a, const pair<pii, bool> &b) {
return a.first.second > b.first.second;
});
for (int i = 0; i < k; i++)
{
ans += v[i].X.X;
v[i].Y = true;
}
// 주최자 점수 순 정렬
sort(v.begin(), v.end(), greater<>());
for (int i = 0; m ; i++) …
```
=> [kjhonggg95] 2023. 11. 12

ddingmin/baekjoon/14618.py, ddingmin/baekjoon/18188.py, ddingmin/baekjoon/19845.py, ddingmin/baekjoon/20924.py, ddingmin/baekjoon/25391.py, ddingmin/baekjoon/25710.py
https://www.acmicpc.net/problem/25391
심판은 항상 상위 k명을 뽑아야 하기에 먼저 k명을 뽑고, 새로운 배열에 뽑히지 않은 인원들을 배치한다.
주최자의 점수 순으로 정렬해 m명 뽑아가면 해결
``` python
import sys
def solve(n, m, k, arr):
answer = 0
arr.sort(key=lambda x: [-x[1], -x[0]])
new_arr = []
for i in range(k):
a, b = arr[i]
answer += a
for i in range(k, n):
a, b = arr[i]
new_arr.append([a, b])
new_arr.sort(key=lambda x: [-x[0], -x[1]])
for i in range(m):
a, b = new_arr[i]
answer += a
return answer
def main():
n, m, k = map(int, input().split())
arr = []
for idx in range(n):
a, b = map(int, input().split())
arr.append([a, b])
print(solve(n, m, k, arr))
main()
```
=> [ddingmin] 2023. 11. 12

ajsthfldu/baekjoon/25391.py
https://www.acmicpc.net/problem/25391
본상은 심판 점수 기준 상위 k명을 뽑는다.
특별상은 주최자 점수 기준 순위 상위 m명을 뽑는데 만약 심판 점수 기준 상위 k명안에 있는 학생이면 건너뛴다.
``` python
import sys
def main():
n, m, k = map(int, sys.stdin.readline().split())
score = [tuple(map(int, sys.stdin.readline().split())) for _ in range(n)]
a_sort = sorted(score, reverse=True)
b_sort = sorted(score, key=lambda x: x[1], reverse=True)
selected = set(b_sort[:k])
i = 0
j = 0
while j < m:
if a_sort[i] in selected:
i += 1
continue
selected.add(a_sort[i])
j += 1
print(sum([a for a, b in selected]))
main()
```
=> [ajsthfldu] 2023. 11. 13

dydwo0740/baekjoon/25391.java
https://www.acmicpc.net/problem/25391
해당 문제는 우선순위 큐를 활용하여 주최자의 점수와 심판의 점수를 객체에 담에 정렬하는 것이 핵심입니다.
어차피 주최자는 자기 마음대로 고를 수 있으므로 심판의 점수에 따른 내림차순 단, 점수가 같을 때 주최자의 점수에 맞게 내림차순합니다. 여기서 중요한 점은 long 자료형을 활용해야 한다는 것입니다. 
``` java
static class Point{
int honor;
int referee;
public Point(int honor, int referee) {
this.honor = honor;
this.referee = referee;
}
}
int K = …
```
=> [dydwo0740] 2023. 11. 12 

dydwo0740/baekjoon/30108.java
https://www.acmicpc.net/problem/30108
heapify 최대힙이라는 느낌을 받았다. 어떤 노드가 포함되면 그 노드의 모든 부모노드는 포함된다.
그리고 그냥 노드의 값을 내림차순해서 누적합으로 결괏값을 도출하면 되는 문제입니다.
생각해보면 간단합니다.
``` java
import java.awt.*;
Integer[] seq = new Integer[N];
for(int i=0;i<N;i++){
seq[i] = Integer.parseInt(st.nextToken());
}
Arrays.sort(seq, Collections.reverseOrder());
long sum = 0;
for(int …
```
=> [dydwo0740] 2023. 11. 13

ddingmin/baekjoon/14618.py, ddingmin/baekjoon/18188.py, ddingmin/baekjoon/19845.py, ddingmin/baekjoon/20924.py, ddingmin/baekjoon/25391.py, ddingmin/baekjoon/25710.py, ddingmin/baekjoon/30108.py
https://www.acmicpc.net/problem/30108
> [Prim's algorithm](https://www.weeklyps.com/entry/%ED%94%84%EB%A6%BC-%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%A6%98-Prims-algorithm) 논리와 비슷하게 적용하면 쉽게 풀 수 있다.
문제를 잘 읽어보면 트리의 루트 노드를 시작으로 이어질 수 있는 노드들 중에 가장 큰 값을 가진 노드들을 순서대로 이어주어 답을 구해나가야 한다.
1. 단방향으로 adj를 만들어준다.
2. 루트 노드를 시작으로 이동할 수 있는 노드들을 최대힙에 삽입한다.
3. 가장 큰 값들을 순서대로 꺼내어 트리를 모두 순회시킨다.
4. 순회 시키는 과정에서 합들을 구해나간다.
``` python
import sys
import heapq
def solve(n, adj, node):
answer = [0]
start = 1
hq = []
heapq.heappush(hq, [-1 * node[start - 1], start])
while hq:
dist, cur = heapq.heappop(hq)
answer.append((-1 * dist) + answer[-1])
for nxt in adj[cur]:
heapq.heappush(hq, [-1 * node[nxt - 1], nxt])
return answer[1:]
def main():
adj = [[] for _ in range(n + 1)]
p = …
```
=> [ddingmin] 2023. 11. 13

kjhonggg95/baekjoon/14618.cpp, kjhonggg95/baekjoon/15809.cpp, kjhonggg95/baekjoon/18188.cpp, kjhonggg95/baekjoon/19845.cpp, kjhonggg95/baekjoon/20924.cpp, kjhonggg95/baekjoon/25391.cpp, kjhonggg95/baekjoon/27942.cpp, kjhonggg95/baekjoon/30108.cpp
[30108번: 교육적인 트리 문제](https://www.acmicpc.net/problem/30108)
1. 우선순위 큐
각 정점마다 {자식 노드 정수, 자식 노드 번호} 정보를 담아놓고 1번노드부터 시작해 우선순위 큐에 정수가 높은 순으로 담는다.
하나씩 빼면서 더하면 정점의 개수마다 최대값을 구할 수 있다.
2. 그리디
`또한, A_i <= A_p_i 라는 특수한 성질을 만족한다. ` 라는 조건때문에 큰 순서대로 더해나가면 된다.
1) 우선순위 큐
```  c++
int n, x, cnt;
int p[300001];
ll mx;
vector<pii> v[300001];
int main()
{
fastio;
priority_queue<pii> pq;
cin >> n;
for (int i = 2; i <= n; i++)
cin >> p[i];
cin >> x;
pq.push({x, 1});
for (int i = 2; i <= n; i++)
{
cin >> x;
v[p[i]].push_back({x, i}); // 부모 (점수, 자식)
}
while (!pq.empty())
{
auto cur = …
```
=> [kjhonggg95] 2023. 11. 13

kjhonggg95/baekjoon/10429.cpp, kjhonggg95/baekjoon/14618.cpp, kjhonggg95/baekjoon/15809.cpp, kjhonggg95/baekjoon/18188.cpp, kjhonggg95/baekjoon/19845.cpp, kjhonggg95/baekjoon/20924.cpp, kjhonggg95/baekjoon/25391.cpp, kjhonggg95/baekjoon/27942.cpp, kjhonggg95/baekjoon/30108.cpp
[10429번: QUENTO](https://www.acmicpc.net/problem/10429)
백트래킹으로 탐색하면서 각 칸이 숫자인지 연산자인지에 따라 케이스를 나눠준다.
숫자 `M`개를 이용했을 때 결과가 `N`이 나온다면 경로를 출력해주고 `exit()` 함수로 바로 종료하도록 함.
``` c++
int dx[4] = {1, 0, -1, 0};
int dy[4] = {0, 1, 0, -1};
int n, m;
bool vis[3][3];
char arr[3][3];
void dfs(int r, int c, int res, int cnt, char prev, vector<pii> v)
{
v.push_back({r, c});
// 현재 칸이 숫자인 경우
if (arr[r][c] >= '1' && arr[r][c] <= '9')
{
if (prev == '+')
res += (arr[r][c] - '0');
else if (prev == '-')
res -= (arr[r][c] - '0');
cnt++;
if (cnt == m)
{
if (res == n)
{
cout << 1 << '\n';
for (auto e : v)
cout << e.X << ' …
```
=> [kjhonggg95] 2023. 11. 14

dydwo0740/baekjoon/10429.java
https://www.acmicpc.net/problem/10429
3 X 3 문제이므로 시간복잡도는 생각하지 않고 완전탐색으로 풀었습니다. 우선 숫자를 만나게 된다면 
숫자 기호 숫자 이런식으로 접근을 하게됩니다.
그렇게 해서 총합이 N과 같으면 저장후 반환합니다.
``` java
static int N;
static int M;
static char[][] board = new char[3][3];
int x;
int y;
public Node(int x, int y) {
this.x = x;
this.y = y;
}
}
static List<Node> list = new ArrayList<>();
static List<Node> ans = new ArrayList<>();
static boolean flag = false;
BufferedWriter bw = new …
```
=> [dydwo0740] 2023. 11. 14

kjhonggg95/baekjoon/10429.cpp, kjhonggg95/baekjoon/14618.cpp, kjhonggg95/baekjoon/14658.cpp, kjhonggg95/baekjoon/15809.cpp, kjhonggg95/baekjoon/18188.cpp, kjhonggg95/baekjoon/19845.cpp, kjhonggg95/baekjoon/20924.cpp, kjhonggg95/baekjoon/25391.cpp, kjhonggg95/baekjoon/27942.cpp, kjhonggg95/baekjoon/30108.cpp
[14658번: 하늘에서 별똥별이 빗발친다](https://www.acmicpc.net/problem/14658)
처음에는 각 별똥별의 위치를 원점으로 잡았을 때 `l`만큼 길이의 1, 2, 3, 4분면을 탐색했다.
하지만 이런식으로 탐색하면
위와 같은 경우 `l`이 3일 때 4개의 별똥별을 모두 튕겨내는 트램펄린을 설치하지 못하게 된다.
그래서 위와 같이 모든 별똥별들의 x좌표와 y좌표들로 조합 가능한 기준점에 대해 해당 범위의 별똥별의 개수를 카운트했다.
``` python java c++
int n, m, l, k, mx;
int main()
{
fastio;
cin >> n >> m >> l >> k;
vector<pii> star(k);
for(int i = 0;i<k;i++)
cin >> star[i].X >> star[i].Y;
for(auto& a : star)
{
for(auto& b : star)
{
int x = a.X, y = b.Y, cnt = 0;
for(auto& e : star)
if(e.X >= x && e.X <= x + l && e.Y >= y && e.Y <= y + l) cnt++;
mx = max(mx, cnt);
}
} …
```
=> [kjhonggg95] 2023. 11. 15

kjhonggg95/baekjoon/10429.cpp, kjhonggg95/baekjoon/14618.cpp, kjhonggg95/baekjoon/14658.cpp, kjhonggg95/baekjoon/15809.cpp, kjhonggg95/baekjoon/16197.cpp, kjhonggg95/baekjoon/18188.cpp, kjhonggg95/baekjoon/19845.cpp, kjhonggg95/baekjoon/20924.cpp, kjhonggg95/baekjoon/25391.cpp, kjhonggg95/baekjoon/27942.cpp, kjhonggg95/baekjoon/30108.cpp
[16197번: 두 동전](https://www.acmicpc.net/problem/16197)
큐에 {동전1 위치, 동전2 위치, 이동 횟수} 를 넣어가면서 BFS로 탐색한다.
바깥으로 나갔을 경우의 인덱스를 체크하기 위해 격자의 맨 왼쪽 위를 (1, 1)로 잡고 시작했다.
보드 크기와 최대 이동 횟수가 작아서 방문 체크를 안해줬었는데 하고 나니까 시간이랑 메모리가 대폭 줄어들었다~
```  c++
int dx[4] = {1, 0, -1, 0};
int dy[4] = {0, 1, 0, -1};
char arr[25][25];
bool vis[25][25][25][25];
int n, m, ans;
struct pos
{
pii coin1;
pii coin2;
int cnt;
};
int main()
{
fastio;
pii coin1, coin2;
int cnt = 0;
cin >> n >> m;
for (int i = 1; i <= n; i++)
{
string s;
cin >> s;
for (int j = 1; j <= m; j++)
{
arr[i][j] = s[j - 1];
if (arr[i][j] == 'o')
{
if (cnt == 0)
{
coin1 …
```
=> [kjhonggg95] 2023. 11. 16

ajsthfldu/baekjoon/16197.py
https://www.acmicpc.net/problem/16197
bfs로 탐색하는데 두 동전에 대해 조건을 확인한다.
방문체크를 하면 시간을 많이 줄일 수 있다.
``` python
import sys
def findStart():
start_a = (0, 0)
start_b = (0, 0)
is_first = True
for i in range(n):
for j in range(m):
if board[i][j] == 'o':
if is_first:
start_a = (i, j)
is_first = False
else:
start_b = (i, j)
return start_a, start_b
def bfs(start_a, start_b):
queue = deque([(start_a, start_b, 0)])
visited[start_a[0]][start_a[1]][start_b[0]][start_b[1]] = True
visited[start_b[0]][start_b[1]][start_a[0]][start_a[1]] = True
while queue:
current_a, current_b, current_step, = queue.popleft()
if current_step >= 10:
return -1
next_step = current_step + 1
next_a = current_a[0] + dx[i], current_a[1] + dy[i]
next_b = current_b[0] + dx[i], …
```
=> 2023. 11. 16

dydwo0740/baekjoon/16197.java
https://www.acmicpc.net/problem/16197
두 코인은 움직임이 동일합니다. 만약 코인이 벽에 부딪히거나 겹치게 된다면 다시 원래 위치로 dfs를 진행하고
한 코인만 떨어졌다면 초기화를 진행합니다.
``` java
import javax.lang.model.SourceVersion;
static int N;
static int M;
static char[][] board;
static int ans = Integer.MAX_VALUE;
N = …
```
=> [dydwo0740] 2023. 11. 16

ddingmin/baekjoon/10429.py, ddingmin/baekjoon/14618.py, ddingmin/baekjoon/18188.py, ddingmin/baekjoon/19845.py, ddingmin/baekjoon/20924.py, ddingmin/baekjoon/25391.py, ddingmin/baekjoon/25710.py, ddingmin/baekjoon/30108.py
https://www.acmicpc.net/problem/10429
숫자와 기호를 잘 분리해서 백트래킹 DFS를 통해 완전 탐색하면 간단하게 풀린다.
``` python
import sys
def is_numeric(s):
try:
value = int(s)
return True
except ValueError:
return False
def solve(n, m, arr):
dx, dy = [-1, 1, 0, 0], [0, 0, -1, 1]
visit = [[0] * 3 for _ in range(3)]
answer_cmd = None
def backtracking(i, j, cmd, total, target, depth):
nonlocal answer_cmd
if depth == 0:
if total == target:
answer_cmd = str(cmd)
return
x, y = i + dx[k], j + dy[k]
if not (0 <= x < 3 and 0 <= y < 3) or visit[x][y] == 1:
continue
visit[x][y] = 1
if is_numeric(arr[x][y]):
if arr[i][j] == '+':
backtracking(x, y, cmd + f"\n{x} {y}", total + int(arr[x][y]), target, depth - 1)
else:
backtracking(x, y, cmd + f"\n{x} {y}", total - int(arr[x][y]), target, depth - 1)
else: …
```
=> [ddingmin] 2023. 11. 14

ddingmin/baekjoon/10429.py, ddingmin/baekjoon/14618.py, ddingmin/baekjoon/16197.py, ddingmin/baekjoon/18188.py, ddingmin/baekjoon/19845.py, ddingmin/baekjoon/20924.py, ddingmin/baekjoon/25391.py, ddingmin/baekjoon/25710.py, ddingmin/baekjoon/30108.py
https://www.acmicpc.net/problem/16197
두 동전이 동일하게 움직인다. 벽에 도달하는 경우 움직이지 않도록 잘 구현해주면 된다.
10번의 움직임까지만 가능하므로 예외처리를 잘 해주자.
``` python
import sys
def move(arr, n, m, i, j, x, y):
if not (0 <= x < n and 0 <= y < m):
return x, y
if arr[x][y] == '#':
return i, j
return x, y
def solve(n, m, arr, coins):
dx, dy = [-1, 1, 0, 0], [0, 0, -1, 1]
q = deque()
q.append(coins)
visit = {}
visit[str(coins)] = 1
depth = 1
while q:
if depth > 10:
return -1
for _ in range(len(q)):
coin = q.popleft()
i1, j1 = coin[0]
i2, j2 = coin[1]
x1, y1 = move(arr, n, m, i1, j1, i1 + dx[k], j1 + dy[k])
x2, y2 = move(arr, n, m, i2, j2, i2 + dx[k], j2 + dy[k])
nxt = [[x1, y1], [x2, y2]]
if str(nxt) in visit: continue
if not (0 <= x1 < n and 0 <= y1 < m) and not (0 <= x2 < n and 0 …
```
=> [ddingmin] 2023. 11. 16

kjhonggg95/baekjoon/10429.cpp, kjhonggg95/baekjoon/14618.cpp, kjhonggg95/baekjoon/14658.cpp, kjhonggg95/baekjoon/15809.cpp, kjhonggg95/baekjoon/16197.cpp, kjhonggg95/baekjoon/18188.cpp, kjhonggg95/baekjoon/19845.cpp, kjhonggg95/baekjoon/20924.cpp, kjhonggg95/baekjoon/25391.cpp, kjhonggg95/baekjoon/27942.cpp, kjhonggg95/baekjoon/30108.cpp, kjhonggg95/baekjoon/9694.cpp
[9694번: 무엇을 아느냐가 아니라 누구를 아느냐가 문제다](https://www.acmicpc.net/problem/9694)
다익스트라 + 경로복원
딱히 특별한건 없다
``` c++
int t, n, m, u, v, w;
int d[21];
int prv[21];
void print(int cur)
{
if (cur == -1)
return;
print(prv[cur]);
cout << cur << ' ';
}
int main()
{
fastio;
cin >> t;
for (int tc = 1; tc <= t; tc++)
{
cin >> n >> m;
fill(d, d + m + 1, 1e9);
fill(prv, prv + m + 1, -1);
vector<pii> adj[m];
while (n--)
{
cin >> u >> v >> w;
adj[u].push_back({w, v});
adj[v].push_back({w, u});
}
priority_queue<pii, vector<pii>, greater<pii>> pq;
d[0] = 0;
pq.push({d[0], 0});
while (!pq.empty())
{
auto cur = pq.top(); …
```
=> [kjhonggg95] 2023. 11. 17

qsunki/baekjoon/30108.py
https://www.acmicpc.net/problem/30108
처음에는 트리를 만들고 우선순위 큐를 만들어 가장 큰 값을 가진 정점을 빼고 그것의 자식 정점을 큐에 넣는 식으로 풀었다.
그런데 다른 사람의 풀이를 보니 정렬만으로 풀 수 있는 문제라는 걸 알았다.
정점을 선택할 때에는 그 정점의 부모 정점이 선택되어야 하는데 부모 정점은 항상 자식 정점보다 크거나 같기 때문에 정렬만으로 풀 수 있는 문제였다.
``` python
import sys
from heapq import *
def search(graph, values, n):
ans = []
pq = []
heappush(pq, (-values[1], 1))
sum_ = 0
while n > 0:
value, parent = heappop(pq)
sum_ += value
for child in graph[parent]:
heappush(pq, (-values[child], child))
ans.append(-sum_)
n -= 1
return ans
def main():
graph = [[] for _ in range(n + 1)]
p = [0, 0] + list(map(int, sys.stdin.readline().split()))
for i in range(2, n + 1):
graph[p[i]].append(i)
values = [0] + list(map(int, sys.stdin.readline().split()))
ans = search(graph, values, n) …
```
=> [ajsthfldu] 2023. 11. 17

dydwo0740/baekjoon/9694.java
https://www.acmicpc.net/problem/9694
dijkstra를 사용해서 풀이를 진행합니다.
dijkstra로 갱신이 이루어질때마다 prev 배열에 이전에 값을 저장합니다.
역으로 값을 빼내서 진행합니다.
``` java
static class Node{
int v;
int cost;
public Node(int v, int cost) {
this.v = v;
this.cost = cost;
}
}
static int N;
static int M;
static List<Node>[] g;
static int[] prev;
for (int test = 1; test <= T; test++) {
M = …
```
=> [dydwo0740] 2023. 11. 17

ddingmin/baekjoon/10429.py, ddingmin/baekjoon/14618.py, ddingmin/baekjoon/16197.py, ddingmin/baekjoon/18188.py, ddingmin/baekjoon/19845.py, ddingmin/baekjoon/20924.py, ddingmin/baekjoon/25391.py, ddingmin/baekjoon/25710.py, ddingmin/baekjoon/30108.py, ddingmin/baekjoon/9694.py
https://www.acmicpc.net/problem/9694
다익스트라를 이용해서 목표 노드에 도달하는 최소 거리를 구하는 문제이다. 중요한 것은 경로를 출력해야하기 때문에 prev 배열을 통해 재귀적으로 특정 노드로부터 출발 위치를 찾아낼 수 있도록 하는 배열을 만들어 **`최소거리 갱신마다`** 구현해주어야 한다.
``` python
import sys
def is_numeric(s):
try:
value = int(s)
return True
except ValueError:
return False
def solve(n, m, arr):
dx, dy = [-1, 1, 0, 0], [0, 0, -1, 1]
visit = [[0] * 3 for _ in range(3)]
answer_cmd = None
def backtracking(i, j, cmd, total, target, depth):
nonlocal answer_cmd
if depth == 0:
if total == target:
answer_cmd = str(cmd)
return
x, y = i + dx[k], j + dy[k]
if not (0 <= x < 3 and 0 <= y < 3) or visit[x][y] == 1:
continue
visit[x][y] = 1
if is_numeric(arr[x][y]):
if arr[i][j] == '+':
backtracking(x, y, cmd + f"\n{x} {y}", total + int(arr[x][y]), target, depth - 1)
else: …
```
=> [ddingmin] 2023. 11. 17

qsunki/baekjoon/10429.py
https://www.acmicpc.net/problem/10429
깊이우선탐색/백트래킹을 하면서 기호일 때와 숫자일 때 분기를 잘 나눠서 푼다.
``` python
import sys
def dfs(visited, route, num, cnt):
cx = route[-1][0]
cy = route[-1][1]
operator = graph[cx][cy]
nx = cx + dx[i]
ny = cy + dy[i]
if nx < 0 or nx >= 3 or ny < 0 or ny >= 3:
continue
if visited[nx][ny]:
continue
if operator.isnumeric():
route.append((nx, ny))
visited[nx][ny] = True
ans = dfs(visited, route, num, cnt)
if ans == 1:
return 1
route.pop()
visited[nx][ny] = False
continue
n_num = num
if operator == '+':
n_num += int(graph[nx][ny])
if operator == '-':
n_num -= int(graph[nx][ny])
n_cnt = cnt + 1
route.append((nx, ny))
if n_cnt == m and n_num == n:
return 1
if n_cnt >= m:
route.pop()
continue
visited[nx][ny] = True
ans = dfs(visited, route, n_num, n_cnt)
if ans …
```
=> [ajsthfldu] 2023. 11. 18

ddingmin/baekjoon/10429.py, ddingmin/baekjoon/14618.py, ddingmin/baekjoon/15809.py, ddingmin/baekjoon/16197.py, ddingmin/baekjoon/18188.py, ddingmin/baekjoon/19845.py, ddingmin/baekjoon/20924.py, ddingmin/baekjoon/25391.py, ddingmin/baekjoon/25710.py, ddingmin/baekjoon/30108.py, ddingmin/baekjoon/9694.py
[15809번: 전국시대](https://www.acmicpc.net/problem/15809)
유니온 파인드 문제이다. 주어진 cmd가 전쟁, 동맹을 할 때마다 유니온 파인드와 함께 병력을 부모 노드로 몰아주어 해결하면 된다.
주의할 점은 두 나라가 전쟁해서 병력이 모두 0이되면 두 나라는 답에서 제외시켜주어야 한다.
``` python
import sys
def find(parents, cur):
if parents[cur] == -1:
return -1
if parents[cur] == cur:
return cur
parents[cur] = find(parents, parents[cur])
return parents[cur]
def union(parents, nodes, a, b):
ap = find(parents, a)
bp = find(parents, b)
parents[bp] = ap
nodes[ap] += nodes[bp]
nodes[bp] = 0
def fight(parents, nodes, a, b):
ap = find(parents, a)
bp = find(parents, b)
if nodes[ap] < nodes[bp]:
ap, bp = bp, ap
elif nodes[ap] == nodes[bp]:
parents[ap], parents[bp] = -1, -1
parents[bp] = ap
nodes[ap] -= nodes[bp]
nodes[bp] = 0
def solve(n, m, nodes, parents, cmds):
for cmd, p, q in cmds:
p, q = p - 1, …
```
=> [ddingmin] 2023. 11. 07

kjhonggg95/baekjoon/10429.cpp, kjhonggg95/baekjoon/14618.cpp, kjhonggg95/baekjoon/14658.cpp, kjhonggg95/baekjoon/14722.cpp, kjhonggg95/baekjoon/15809.cpp, kjhonggg95/baekjoon/16197.cpp, kjhonggg95/baekjoon/18188.cpp, kjhonggg95/baekjoon/19845.cpp, kjhonggg95/baekjoon/20924.cpp, kjhonggg95/baekjoon/25391.cpp, kjhonggg95/baekjoon/27942.cpp, kjhonggg95/baekjoon/30108.cpp, kjhonggg95/baekjoon/9694.cpp
[14722번: 우유 도시](https://www.acmicpc.net/problem/14722)
**dp**
_(N, N)_ 부터 시작하는 top-down dp로 답을 구하였다.
현재 칸을 기준으로 위쪽/왼쪽에서 오는 길 중 어느 쪽으로 오는게 최대인지 구한다.
dp 배열에는 {현재 칸까지 오면서 최근에 마신 우유, 현재까지 마신 우유의 수} 를 저장한다.
주의할 점은 시작점이 딸기우유(0)가 아닐 수도 있다는 것.
즉, 우유를 처음 먹는 시점은 이동하면서 최초로 딸기우유(0)를 만났을 때다.
그렇기 때문에 dp[1][1] 을 시작점이 딸기우유라면 {0, 1}, 아니라면 {2, 0} 로 초기화하고 진행했다.
``` c++
int n;
int arr[1001][1001];
pii dp[1001][1001]; // [i][j] : i, j 칸에 도달했을 때 {최근에 마신 우유, 지금까지 마신 우유의 수}
// 0 딸기우유
// 1 초코우유
// 2 바나나우유
// 딸기 -> 초코 -> 바나나 -> 딸기 -> ...
// 이동
// 1) 동쪽
// 2) 남쪽
pii func(int r, int c)
{
if (r <= 0 || c <= 0)
return {-1e9, …
```
=> [kjhonggg95] 2023. 11. 18

kjhonggg95/baekjoon/10429.cpp, kjhonggg95/baekjoon/14618.cpp, kjhonggg95/baekjoon/14658.cpp, kjhonggg95/baekjoon/14722.cpp, kjhonggg95/baekjoon/15809.cpp, kjhonggg95/baekjoon/16197.cpp, kjhonggg95/baekjoon/18188.cpp, kjhonggg95/baekjoon/19845.cpp, kjhonggg95/baekjoon/20924.cpp, kjhonggg95/baekjoon/25391.cpp, kjhonggg95/baekjoon/27942.cpp, kjhonggg95/baekjoon/30108.cpp, kjhonggg95/baekjoon/5547.cpp, kjhonggg95/baekjoon/9694.cpp
[5547번: 일루미네이션](https://www.acmicpc.net/problem/5547)
문제에서 주어진 그림과 다르게 나는 행과 열을 이용해서 풀었다.
그러면 문제에서 주어진 그림 속 격자 안의 x, y 위치가 바뀌게 된다. _ex) (2, 3) -> (3, 2)_
한 격자에서 맞닿아있는 격자들의 위치가 어떻게 구성되어있나를 잘 관찰하면 쉽게 풀 수 있다.
1) 격자가 홀수 행에 위치할 때
----(r-1, c)--(r-1, c+1)
(r, c-1)-- _**(r, c)**_--(r, c+1)
----(r+1, c)--(r-1, c+1)
2) 격자가 짝수 행에 위치할 때
--(r-1, c-1)--(r-1, c)
(r, c-1)-- _**(r, c)**_--(r, c+1)
--(r+1, c-1)--(r-1, c)
바깥에 있는 벽면의 길이를 구해야 하므로 BFS를 건물의 바깥쪽에서 시작한다. (0, 0)
이 때 그림에 나와있는 격자판을 둘러싸는 격자를 한 겹 더 두른다는 것이 중요하다.
흰색 격자들을 모두 탐색하면서 맞닿아 있는 격자의 수를 카운트해주면 된다.
``` c++
int dx[6] = {-1, -1, 0, 0, 1, 1};
int dy[6] = …
```
=> [kjhonggg95] 2023. 11. 19

dydwo0740/baekjoon/10710.java
https://www.acmicpc.net/problem/10710
dp로 접근을 해야했습니다. 해당 문제에서 이차원 배열을 선언하고 첫번째 index가 목적지 두번째 index가 도달한 날짜
라고 생각을 하고  dp[i][j] = Math.min(dp[i-1][k] + cost[j] * dist[i], dp[i][j]); 해당 점화식을 활용하였습니다.
``` java
int index;
int value;
public Node(int index, int value) {
this.index = index;
this.value = value;
}
}
int[] dist = new int[N];
int[] cost = new int[M];
for (int i …
```
=>  [BOJ] 10710: 실크로드

ddingmin/baekjoon/10429.py, ddingmin/baekjoon/12886.py, ddingmin/baekjoon/14618.py, ddingmin/baekjoon/14722.py, ddingmin/baekjoon/15809.py, ddingmin/baekjoon/16197.py, ddingmin/baekjoon/18188.py, ddingmin/baekjoon/19845.py, ddingmin/baekjoon/20924.py, ddingmin/baekjoon/25391.py, ddingmin/baekjoon/25710.py, ddingmin/baekjoon/27942.py, ddingmin/baekjoon/30108.py, ddingmin/baekjoon/4920.py, ddingmin/baekjoon/9694.py
[12886: 돌 그룹](https://www.acmicpc.net/problem/12886)
3개의 돌 그룹을 주어진 방법으로 나누어 모두 같은 갯수의 돌로 나눌 수 있는지 찾는 문제이다.
BFS 탐색을 통해 구현할 수 있다.
pypy는 500 * 500 * 500의 메모리가 터져서 dict(HashMap)을 통해 방문 체크 한 뒤 풀이했다.
``` python
import sys
def calc(x, y):
if x < y:
return x + x, y - x
else:
return x - y, y + y
def get_abc(i, j, k):
result = []
a, b = calc(i, j)
result.append([a, b, k])
b, c = calc(j, k)
result.append([i, b, c])
a, c = calc(i, k)
result.append([a, j, c])
return result
def solve(a, b, c):
visit = {}
visit[a, b, c] = True
q = deque()
q.append([a, b, c])
while q:
i, j, k = q.popleft()
if i == j == k:
return 1
for a, b, c in get_abc(i, j, k):
if (a, b, c) in visit: continue
q.append([a, b, c])
visit[a, b, c] = True
return 0
def main():
a, b, c = map(int, input().split()) …
```
=> [ddingmin] 2023. 11. 21

kjhonggg95/baekjoon/10429.cpp, kjhonggg95/baekjoon/10710.cpp, kjhonggg95/baekjoon/12886.cpp, kjhonggg95/baekjoon/14618.cpp, kjhonggg95/baekjoon/14658.cpp, kjhonggg95/baekjoon/14722.cpp, kjhonggg95/baekjoon/15809.cpp, kjhonggg95/baekjoon/16197.cpp, kjhonggg95/baekjoon/18188.cpp, kjhonggg95/baekjoon/19845.cpp, kjhonggg95/baekjoon/20924.cpp, kjhonggg95/baekjoon/25391.cpp, kjhonggg95/baekjoon/27942.cpp, kjhonggg95/baekjoon/30108.cpp, kjhonggg95/baekjoon/5547.cpp, kjhonggg95/baekjoon/9694.cpp
[10710번: 실크로드](https://www.acmicpc.net/problem/10710)
`i`번째 날 `j`번째 도시에 있을 때 최소 피로도를 저장하는 2차원 배열 `dp[i][j]` 에 DP값을 저장한다.
`i`번째 날 `j`번 도시에 있을 때 피로도의 최소값은
* `i - 1`번째 날까지 `j`번 도시에 있다가 `i`번째 날에도 `j`번 도시에 머무르는 경우 (stay)
* `i - 1`번째 날까지 `j - 1`번 도시에 있다가 `i`번째 날에 `j`번 도시로 이동하는 경우 (move)
위 두 케이스 중 최소값
``` c++
int d[1005];        // 거리
int w[1005];        // 날씨 나쁨정도
int dp[1005][1005]; // [i][j] : i번째 날 j번째 도시를 갈 때 최소 피로도
// 10 25 15
// 50 30 15 40 30
int main()
{
fastio;
memset(dp, 0x7f, sizeof(dp));
int n, m;
cin >> n >> m;
for (int i = 1; i <= n; i++)
cin >> d[i];
for (int i = 1; i <= m; i++)
cin >> …
```
=> [kjhonggg95] 2023. 11. 20~21

ddingmin/baekjoon/10429.py, ddingmin/baekjoon/12886.py, ddingmin/baekjoon/14618.py, ddingmin/baekjoon/14722.py, ddingmin/baekjoon/15809.py, ddingmin/baekjoon/16197.py, ddingmin/baekjoon/18188.py, ddingmin/baekjoon/19538.kt, ddingmin/baekjoon/19845.py, ddingmin/baekjoon/20924.py, ddingmin/baekjoon/25391.py, ddingmin/baekjoon/25710.py, ddingmin/baekjoon/27942.py, ddingmin/baekjoon/30108.py, ddingmin/baekjoon/4920.py, ddingmin/baekjoon/9694.py
[19538: 루머](https://www.acmicpc.net/problem/19538)
bfs 문제이지만 루머를 믿는 조건과 해당 경우의 위치를 잘 지정해서 풀어야 한다.
``` kotlin
import java.io.BufferedWriter
import java.io.OutputStreamWriter
fun main() = with(System.`in`.bufferedReader()) {
val sout = BufferedWriter(OutputStreamWriter(System.out))
var n = readLine().toInt()
var adj = Array(n) {
ArrayList<Int>()
}
repeat(n) {
readLine().split(" ").map { num ->
if (num.toInt() > 0) adj[it].add(num.toInt() - 1)
}
}
var m = readLine().toInt()
var start = readLine().split(" ").map { it.toInt() - 1 }
sout.appendLine(solve(n, adj, start))
sout.close()
}
fun solve(n: Int, adj: Array<ArrayList<Int>>, start: List<Int>): String {
var answer = IntArray(n) { -1 }
var count = IntArray(n)
var visit = BooleanArray(n)
start.map {
answer[it] = 0
visit[it] = true
adj[it].map …
```
=> [ddingmin] 2023. 11. 22

kjhonggg95/baekjoon/10429.cpp, kjhonggg95/baekjoon/10710.cpp, kjhonggg95/baekjoon/12886.cpp, kjhonggg95/baekjoon/14618.cpp, kjhonggg95/baekjoon/14658.cpp, kjhonggg95/baekjoon/14722.cpp, kjhonggg95/baekjoon/15809.cpp, kjhonggg95/baekjoon/16197.cpp, kjhonggg95/baekjoon/18188.cpp, kjhonggg95/baekjoon/19538.cpp, kjhonggg95/baekjoon/19845.cpp, kjhonggg95/baekjoon/20924.cpp, kjhonggg95/baekjoon/25391.cpp, kjhonggg95/baekjoon/27942.cpp, kjhonggg95/baekjoon/30108.cpp, kjhonggg95/baekjoon/5547.cpp, kjhonggg95/baekjoon/9694.cpp
[19538번: 루머](https://www.acmicpc.net/problem/19538)
최초 유포자는 0으로 시작.
BFS로 탐색해가며 `cur` 주위의 사람들(`nxt`)을 살핀다. 
`nxt` 주위에 루머를 믿는 사람의 수(`cnt`)가  절반 이상일 때 큐에 넣고 방문 체크를 해준다.
`nxt`가 루머를 믿기 시작한 시간은 _**절반이 된 시점 + 1**_ 이 되므로 같이 큐에 넣고 탐색을 이어나간다.
``` c++
vector<int> adj[200001];
int rumor[200001]; // 루머를 믿기 시작한 시간
bool vis[200001];
int n, m, x;
int main()
{
fastio;
memset(rumor, -1, sizeof(rumor));
cin >> n;
for (int i = 1; i <= n; i++)
{
while (cin >> x)
{
if (x == 0) break;
adj[i].push_back(x);
}
}
cin >> m;
queue<pii> q;
while (m--)
{
cin >> x;
rumor[x] = 0;
vis[x] = true;
q.push({x, 0});
}
while …
```
=> [kjhonggg95] 2023. 11. 22

qsunki/baekjoon/5546.py
https://www.acmicpc.net/problem/5546
K일에 먹어야 되는 파스타가 주어지지 않았다면
i일에 파스타 X를 먹는 경우의 수는 i - 1일과 i - 2일 각각 X가 아닌 종류의 파스타를 먹는 경우의 수를 합친 것과 같다.
K일에 파스타 Y를 먹어야 된다면 K일에 Y가 아닌 파스타를 먹는 경우의 수는 0이고
K + 1일에 Y가 아닌 파스타를 먹는 경우의 수가 K일에 파스타를 먹는 경우의 수가 된다.
``` python
import sys
n, k = map(int, sys.stdin.readline().split())
days = [-1] * (n + 1)
for _ in range(k):
a, b = map(int, sys.stdin.readline().split())
days[a] = b - 1
dp = [[0] * 3 for _ in range(n + 1)]
dp[1] = [1] * 3
if days[1] != -1:
dp[1] = [0] * 3
dp[1][days[1]] = 1
x = sum(dp[1])
dp[2] = [x] * 3
if days[2] != -1:
dp[2] = [0] * 3
dp[2][days[2]] = x
for i in range(3, n + 1):
dp[i][0] = dp[i - 1][1] + dp[i - 1][2] + dp[i - 2][1] + dp[i - 2][2]
dp[i][1] = dp[i - 1][0] + dp[i - 1][2] + dp[i - 2][0] + dp[i - 2][2]
dp[i][2] = dp[i - 1][0] + dp[i - …
```
=> [ajsthfldu] 2023. 11. 23

kjhonggg95/baekjoon/10429.cpp, kjhonggg95/baekjoon/10710.cpp, kjhonggg95/baekjoon/12886.cpp, kjhonggg95/baekjoon/14618.cpp, kjhonggg95/baekjoon/14658.cpp, kjhonggg95/baekjoon/14722.cpp, kjhonggg95/baekjoon/15809.cpp, kjhonggg95/baekjoon/16197.cpp, kjhonggg95/baekjoon/18188.cpp, kjhonggg95/baekjoon/19538.cpp, kjhonggg95/baekjoon/19845.cpp, kjhonggg95/baekjoon/20924.cpp, kjhonggg95/baekjoon/25391.cpp, kjhonggg95/baekjoon/27942.cpp, kjhonggg95/baekjoon/30108.cpp, kjhonggg95/baekjoon/5546.cpp, kjhonggg95/baekjoon/5547.cpp, kjhonggg95/baekjoon/9694.cpp
[5546번: 파스타](https://www.acmicpc.net/problem/5546)
다음과 같은 점화식을 세워 풀었다.
`dp[i][j][k]` : `i`번째 날에 `j`파스타를 먹는 경우의 수
`k == 0` -> 전날 다른 종류의 파스타를 먹은 상태
`k == 1` -> 이틀 연속으로 `j`파스타를 먹은 상태
``` c++
ll dp[101][3][2];
int pre[101];
// [i][j][k] : i번째날에 j파스타를 먹는 경우의 수
// k : 0 -> 전날 다른 종류를 먹은 상태
// k : 1 -> 이틀 연속으로 먹은 상태
int main()
{
fastio;
int n, k;
cin >> n >> k;
while (k--)
{
int a, b;
cin >> a >> b;
pre[a] = b;
}
if(pre[1] != 0) dp[1][pre[1] - 1][0] = 1;
else dp[1][0][0] = dp[1][1][0] = dp[1][2][0] = 1;
for (int i = 2; i <= n; i++)
{
if(pre[i] != 0)
{  
int k = pre[i] - 1;
dp[i][k][0] = (dp[i-1][(k + 1) …
```
=> [kjhonggg95] 2023. 11. 23

ddingmin/baekjoon/10429.py, ddingmin/baekjoon/10710.py, ddingmin/baekjoon/12886.py, ddingmin/baekjoon/14618.py, ddingmin/baekjoon/14722.py, ddingmin/baekjoon/15809.py, ddingmin/baekjoon/16197.py, ddingmin/baekjoon/18188.py, ddingmin/baekjoon/19538.kt, ddingmin/baekjoon/19845.py, ddingmin/baekjoon/20924.py, ddingmin/baekjoon/25391.py, ddingmin/baekjoon/25710.py, ddingmin/baekjoon/27942.py, ddingmin/baekjoon/30108.py, ddingmin/baekjoon/4920.py, ddingmin/baekjoon/9694.py
[10710번: 실크로드](https://www.acmicpc.net/problem/10710)
날짜와 도시를 2차원 메모제이션를 통해 DP로 해결하면 된다.
0번 도시에 위치하는 경우는 0으로 초기화하고 이동, 이동하지 않는 경우로 최솟값을 갱신해나가자.
``` python java c++
import sys
def solve(n, m, city, arr):
dp = [[float('inf')] * (n + 1) for _ in range(m + 1)]
dp[0][0] = 0
for i in range(1, m + 1):  # 일
for j in range(n + 1):  # 도시
dp[i][j] = min(dp[i - 1][j], dp[i - 1][j - 1] + city[j - 1] * arr[i - 1])
return dp[-1][-1]
def main():
n, m = map(int, input().split())
city = list(int(input()) for _ in range(n))
arr = list(int(input()) for _ in range(m))
print(solve(n, m, city, arr))
main()
```
=> [ddingmin] 2023. 11. 20

ddingmin/baekjoon/10429.py, ddingmin/baekjoon/10710.py, ddingmin/baekjoon/12886.py, ddingmin/baekjoon/14618.py, ddingmin/baekjoon/14658.kt, ddingmin/baekjoon/14658.py, ddingmin/baekjoon/14722.py, ddingmin/baekjoon/15809.py, ddingmin/baekjoon/16197.py, ddingmin/baekjoon/18188.py, ddingmin/baekjoon/19538.kt, ddingmin/baekjoon/19845.py, ddingmin/baekjoon/20924.py, ddingmin/baekjoon/25391.py, ddingmin/baekjoon/25710.py, ddingmin/baekjoon/27942.py, ddingmin/baekjoon/30108.py, ddingmin/baekjoon/4920.py, ddingmin/baekjoon/9694.py
[14658번: 하늘에서 별똥별이 빗발친다](https://www.acmicpc.net/problem/14658)
주어진 n, m의 값은 너무 큰 값이기 때문에 그려서 완전 탐색을 할 수 없다.
하지만 떨어지는 별똥별의 갯수는 100이기 때문에 이를 최대로 활용해서 최적화할 수 있다.
두 별똥별을 경계 영역에 포함시키는 최대 사각형 범위를 찾아 존재하는 별똥별의 개수를 구해주면 된다.
> 최대 사각형 범위: 두 별똥별의 최소 x, y 지점 ~ 각각 +l 한 지점
``` python 
import sys
def solve(n, m, l, k, arr):
answer = 0
for i in range(k):
for j in range(k):
cnt = 0
sx, sy = min(arr[i][0], arr[j][0]), min(arr[i][1], arr[j][1])
for x, y in arr:
if sx <= x <= sx + l and sy <= y <= sy + l:
cnt += 1
answer = max(answer, cnt)
return k - answer
def main():
n, m, l, k = map(int, input().split())
arr = []
for _ in range(k):
arr.append(list(map(int, input().split())))
print(solve(n, m, l, k, arr))
sys.setrecursionlimit(10 ** 5)
main()
```
``` …
```
=> [ddingmin] 2023. 11. 15

kjhonggg95/baekjoon/10429.cpp, kjhonggg95/baekjoon/10710.cpp, kjhonggg95/baekjoon/12764.cpp, kjhonggg95/baekjoon/12886.cpp, kjhonggg95/baekjoon/14618.cpp, kjhonggg95/baekjoon/14658.cpp, kjhonggg95/baekjoon/14722.cpp, kjhonggg95/baekjoon/15809.cpp, kjhonggg95/baekjoon/16197.cpp, kjhonggg95/baekjoon/18188.cpp, kjhonggg95/baekjoon/19538.cpp, kjhonggg95/baekjoon/19845.cpp, kjhonggg95/baekjoon/20924.cpp, kjhonggg95/baekjoon/25391.cpp, kjhonggg95/baekjoon/27942.cpp, kjhonggg95/baekjoon/30108.cpp, kjhonggg95/baekjoon/5546.cpp, kjhonggg95/baekjoon/5547.cpp, kjhonggg95/baekjoon/9694.cpp
[12764번: 싸지방에 간 준하](https://www.acmicpc.net/problem/12764)
총 세 개의 우선순위 큐를 만들어서 풀었다.
1. **입장 우선순위 큐** -> 입장 시간 오름차순
2. **퇴장 우선순위 큐** -> 퇴장 시간 오름차순
3. **자리 최소 번호 우선순위 큐** -> 앉을 수 있는 가장 작은 번호 오름차순
입력으로 들어오는 {시작시간, 종료시간}은 **입장 우선순위 큐**에 삽입한다.
**자리 최소 번호 우선순위 큐**에는 `1 ~ n` 을 미리 넣어놓는다. (최대 n개의 자리 필요)
기본 틀은 `for문`으로 `시간 t`를 `0 ~ 1,000,000` 까지 시뮬레이션한다.
매 시간마다 입장 시간과 퇴장 시간을 체크한다.
입장 시간 일치 시
* `cur = in.top()` : 입장시간/퇴장시간
* `mnseat.top()` : 앉을 수 있는 가장 작은 번호의 자리(`k`)를 찾는다.
* `freq[k]` : k번 자리에 앉은 횟수 카운트
* `seatNo[cur] = k` : 입/퇴장시간이 `cur`인 사람이 k번 자리에 앉음
퇴장 시간 일치 시
* `mnseat.push(seatNo[cur])` : 자리 반납(앉을 수 있는 자리의 가장 작은 번호 갱신)
필요한 컴퓨터의 최소 개수 `X`는 **퇴장 우선순위 큐** 사이즈의 최대 값으로 갱신한다.
```  c++
#define …
```
=> [kjhonggg95] 2023. 11. 24

qsunki/baekjoon/3221.py
https://www.acmicpc.net/problem/3221
1. 개미가 다른 개미를 만날 때 방향을 바꾸기 떄문에 개미들의 순서가 바뀌지 않는다.
2. 개미가 다른 개미를 만나 방향을 바꾸어 이동한 두 위치는 방향을 바꾸지 않고 이동한 두 위치와 같다.
3. 입력 시 왼쪽부터 1번으로 정렬되어 입력되기 때문에 개미들의 최종위치를 정렬하여 출력하면 된다.
4. 개미의 처음위치는 왼쪽 끝에서 오른쪽 방향인 개미의 위치에서 x초 후 모습과 같다. 
5. 왼쪽 끝 오른쪽 방향인 개미의 T + x 초 후 모습을 구하면 최종위치
``` python
import sys
L, T = map(int, sys.stdin.readline().split())
ants_loc = []
for _ in range(n):
loc, direction = sys.stdin.readline().split()
loc = int(loc)
if direction == 'D':
t = T + loc
else:
t = T + 2 * L - loc
remain = t % (2 * L)
if remain <= L:
loc = remain
else:
loc = 2 * L - remain
ants_loc.append(loc)
print(*sorted(ants_loc), sep=' ')
```
=> [ajsthfldu] 2023. 11. 25

ddingmin/baekjoon/10429.py, ddingmin/baekjoon/10710.py, ddingmin/baekjoon/12886.py, ddingmin/baekjoon/14618.py, ddingmin/baekjoon/14658.kt, ddingmin/baekjoon/14658.py, ddingmin/baekjoon/14722.py, ddingmin/baekjoon/15809.py, ddingmin/baekjoon/16197.py, ddingmin/baekjoon/18188.py, ddingmin/baekjoon/19538.kt, ddingmin/baekjoon/19845.py, ddingmin/baekjoon/20924.py, ddingmin/baekjoon/25391.py, ddingmin/baekjoon/25710.py, ddingmin/baekjoon/27942.py, ddingmin/baekjoon/30108.py, ddingmin/baekjoon/3221.py, ddingmin/baekjoon/4920.py, ddingmin/baekjoon/9694.py
https://www.acmicpc.net/problem/3221
개미가 충돌해도 어차피 나아가는 방향 그대로 가도 상관없다.
> 개미가 왼쪽에서 가까운 순서대로 주어지기 때문에 마지막에 정렬해준다
``` python
import sys
def move(direction, cur, l, t):
if direction == 'L':
temp = t - cur
if temp < 0:
return cur - t
if temp // l % 2 == 1:
return l - temp % l
else:
return temp % l
else:
temp = t - (l - cur)
if temp < 0:
return cur + t
if temp // l % 2 == 0:
return l - temp % l
else:
return temp % l
def solve(l, t, cmd):
answer = []
for cur, c in cmd:
answer.append(move(c, int(cur), l, t))
return sorted(answer)
def main():
l, t = map(int, input().split())
cmd = list(input().split() for _ in range(n))
print(*solve(l, t, cmd))
sys.setrecursionlimit(10 ** 5)
main()
```
=> [ddingmin] 2023. 11. 25

dydwo0740/baekjoon/3221.java
https://www.acmicpc.net/problem/3221
개미 클래스를 생성한 후 각각의 개미에 대해 탐색을 한다면 TLE 가 날 수 밖에 없습니다. 
개미가 방향을 바꾸게 되더라도 개미는 진행 방향 그대로 쭉 직진하는 것처럼 보이는 것이 핵심입니다.
고려해야 할 사항은 벽에 튕긴 횟수이므로, 짝수번 튕길시와 홀수번 튕길시 각각의 조건으로
구현을 하면 됩니다.
``` java
//벽에 부딪힌 경우
// 개미에 부딪힌 경우 -> L 은 왼쪽부터, D는 오른쪽부터
List<Integer> answer = new ArrayList<>();
int L = Integer.parseInt(st.nextToken());
int N = …
```
=> [dydwo0740] 2023. 11. 25

qsunki/baekjoon/14618.py
https://www.acmicpc.net/problem/14618
다익스트라
``` python
import sys
from heapq import *
def dijkstra(start):
q = []
distance[start] = 0
heappush(q, (0, start))
while q:
dist, u = heappop(q)
if distance[u] < dist:
continue
for v, w in graph[u]:
if distance[v] <= dist + w:
continue
distance[v] = dist + w
heappush(q, (distance[v], v))
INF = float('inf')
n, m = map(int, sys.stdin.readline().split())
graph = [[] for _ in range(n + 1)]
house = [' '] * (n + 1)
distance = [INF] * (n + 1)
start = int(sys.stdin.readline())
k = int(sys.stdin.readline())
for u in sys.stdin.readline().split():
house[int(u)] = 'A'
for u in sys.stdin.readline().split():
house[int(u)] = 'B'
for _ in range(m):
u, v, w = map(int, sys.stdin.readline().split())
graph[u].append([v, w])
graph[v].append([u, w])
dijkstra(start) …
```
=> [ajsthfldu] 2023. 11. 27

qsunki/baekjoon/9694.py
https://www.acmicpc.net/problem/9694
다익스트라 + 경로
최단거리 갱신 시 이전 노드 경로 + 현재 노드로 구하였다.
``` python
import sys
from heapq import *
def dijkstra(start):
q = []
distance[start] = 0
who_met[start] = [start]
heappush(q, (0, start))
while q:
dist, u = heappop(q)
if distance[u] < dist:
continue
for v, w in graph[u]:
if distance[v] <= dist + w:
continue
distance[v] = dist + w
who_met[v] = who_met[u] + [v]
heappush(q, (distance[v], v))
INF = float('inf')
T = int(sys.stdin.readline())
for t in range(1, T + 1):
n, m = map(int, sys.stdin.readline().split())
graph = [[] for _ in range(m)]
distance = [INF] * m
who_met = [[] for _ in range(m)]
for _ in range(n):
u, v, w = map(int, sys.stdin.readline().split())
graph[u].append([v, w])
graph[v].append([u, w])
dijkstra(0)
if distance[-1] == INF:
print(f'Case …
```
=> [ajsthfldu] 2023. 11. 28

kwyoohae/baekjoon/28291.java
[28291번: 레드스톤](https://www.acmicpc.net/problem/28291)
이번 문제는 레드스톤 전기신호가 lamp까지 도달하는지를 확인하는 문제입니다.
1. bfs로 dust나 lamp가 있는지 확인하고 해당하면 Queue에 추가합니다 
2. 추가할때, 현재 에너지와 가지고 있는 에너지를 비교해서 지금 에너지가 더 크면 light에 에너지를 추가합니다 
3. 한 큐마다, 미리 lamp의 위치를 List에 저장해놓은곳에서 가져와서 모든 lamp가 light가 0 보다 큰지 확인을 합니다
``` python java c++
public static int[] dw = {1, -1, 0, 0};
public static int[] dh = {0, 0, 1, -1};
private static final int DUST = 1;
private static final int BLOCK = 2;
private static final int LAMP = 3;
public static void main(String[] args) throws Exception {
String[] input = br.readLine().split(" ");
int W = …
```
=> [kwyoohae] 2023. 11. 28

kjhonggg95/baekjoon/10429.cpp, kjhonggg95/baekjoon/10710.cpp, kjhonggg95/baekjoon/12764.cpp, kjhonggg95/baekjoon/12886.cpp, kjhonggg95/baekjoon/14618.cpp, kjhonggg95/baekjoon/14658.cpp, kjhonggg95/baekjoon/14722.cpp, kjhonggg95/baekjoon/15809.cpp, kjhonggg95/baekjoon/16197.cpp, kjhonggg95/baekjoon/18188.cpp, kjhonggg95/baekjoon/19538.cpp, kjhonggg95/baekjoon/19845.cpp, kjhonggg95/baekjoon/20924.cpp, kjhonggg95/baekjoon/25391.cpp, kjhonggg95/baekjoon/27942.cpp, kjhonggg95/baekjoon/28291.cpp, kjhonggg95/baekjoon/30108.cpp, kjhonggg95/baekjoon/5546.cpp, kjhonggg95/baekjoon/5547.cpp, kjhonggg95/baekjoon/6086.cpp, kjhonggg95/baekjoon/9694.cpp
[28291번: 레드스톤](https://www.acmicpc.net/problem/28291)
BFS
출발점 : 레드스톤 블록 -> 주위에 15의 전기신호를 주므로 16의 전기신호를 가진 채로 탐색 시작
레드스톤 가루를 통해 전기신호를 전달하는데 현재 칸의 전기신호 - 1이 다음 칸의 전기신호보다 클 경우에만 전기신호 전달
```  c++
#define DUST 1
#define BLOCK 2
#define LAMP 3
int dx[4] = {1, 0, -1, 0};
int dy[4] = {0, 1, 0, -1};
int r, c, rr, cc, n;
int arr[55][55];   // 레드스톤 종류
int power[55][55]; // 가지고 있는 전기신호
set<pii> lamp_pos;
int main()
{
fastio;
cin >> c >> r >> n;
queue<pair<pii, int>> q; // {위치, 전기신호};
for (int i = 0; i < n; i++)
{
string s;
cin >> s >> cc >> rr;
if (s == "redstone_dust")
arr[rr][cc] = DUST;
else if (s == …
```
=> [BOJ] 28291: 레드스톤

kjhonggg95/14925.cpp, kjhonggg95/baekjoon/10429.cpp, kjhonggg95/baekjoon/10710.cpp, kjhonggg95/baekjoon/12764.cpp, kjhonggg95/baekjoon/12886.cpp, kjhonggg95/baekjoon/14618.cpp, kjhonggg95/baekjoon/14658.cpp, kjhonggg95/baekjoon/14722.cpp, kjhonggg95/baekjoon/15809.cpp, kjhonggg95/baekjoon/16197.cpp, kjhonggg95/baekjoon/18188.cpp, kjhonggg95/baekjoon/19538.cpp, kjhonggg95/baekjoon/19845.cpp, kjhonggg95/baekjoon/20924.cpp, kjhonggg95/baekjoon/25391.cpp, kjhonggg95/baekjoon/27942.cpp, kjhonggg95/baekjoon/28291.cpp, kjhonggg95/baekjoon/30108.cpp, kjhonggg95/baekjoon/5546.cpp, kjhonggg95/baekjoon/5547.cpp, kjhonggg95/baekjoon/6086.cpp, kjhonggg95/baekjoon/9694.cpp
[14925번: 목장 건설하기](https://www.acmicpc.net/problem/14925)
좌표 _i, j_ 의 값을 오른쪽 아래 꼭지점이 _i, j_ 인 정사각형의 변의 길이라고 하면
_i, j_ 의 값은
1. _i-1, j_
2. _i, j-1_
3. _i-1, j-1_
위 세 점을 오른쪽 아래 꼭지점으로 하는 정사각형의 길이 중 가장 작은 값 + 1이 된다.
위 그림처럼 (i, j) 의 값이 _n_ 이 되려면 _(i-1, j)_, _(i, j-1)_, _(i-1, j-1)_ 의 값이 모두 n-1이 되어야함.
``` c++
int arr[1001][1001];
int dp[1001][1001];
int main()
{
fastio;
int n, m, ans = 0;
cin >> n >> m;
for (int i = 1; i <= n; i++)
for (int j = 1; j <= m; j++)
cin >> arr[i][j];
for (int i = 1; i <= n; i++)
{
for (int j = 1; j <= m; j++)
{
if (arr[i][j] != 0) continue;
dp[i][j] = min({dp[i - 1][j], dp[i …
```
=> [BOJ] 14925: 목장 건설하기

dydwo0740/baekjoon/4650.java
https://www.acmicpc.net/problem/4650
MST를 활용해서 해결했습니다. 크루스칼 알고리즘을 활용하여, MST를 구하는 과정에서 union이 발생할 시
sum 변수에 값을 더해주는 방식으로 작성했습니다.
``` java
static int N;
static int[] parent;
static class Node{
int v1;
int v2;
int dist;
public Node(int v1, int v2, int dist) {
this.v1 = v1;
this.v2 = v2;
this.dist = dist;
}
}
static int ans = Integer.MAX_VALUE;
StringTokenizer st;
while(true) {
if (N == 0) {
break;
}
PriorityQueue<Node> pq = …
```
=> [BOJ] 4650: Jungle Roads

dydwo0740/baekjoon/2655.java
https://www.acmicpc.net/problem/2655
LIS 를 활용하여 문제를 해결했습니다. 처음에는 최대로 쌓을 수 있는 벽돌의 갯수로 접근을 해서 W/A 결과를 받았습니다.
LIS 를 사용할때, 높이를 기준으로 접근하도록 변경하였고 몇번째 벽돌이 사용되었는지에 대한 문제는 Stack을 활용했습니다. 
경로를 역추적하는 것에 어려움을 겪었고 비슷한 느낌이라고 생각되는 dijkstra 경로 역추적에 대해서 한번 더 생각해봐야겠습니다.
``` java 
int idx;
int size;
int h;
int w;
public Node(int idx, int size, int h, int w) {
this.idx = idx;
this.size = size;
this.h = h;
this.w = w;
}
}
List<Node> seq = new ArrayList<>();
int N = …
```
=> [BOJ] 2655: 가장높은탑쌓기

qsunki/baekjoon/16569.py
https://www.acmicpc.net/problem/16569
화산분출에 따른 지역별 화산재가 덮치는 시간을 기록하고 재상이가 이동하면서 최고높이가 갱신될 때를 기록
``` python
import sys
def volcano_bfs(q):
for x, y, t in q:
volcano_visit_time[x][y] = t
js_visited[x][y] = True
while q:
cx, cy, ct = q.popleft()
nx = cx + dx[i]
ny = cy + dy[i]
nt = ct + 1
if nx < 0 or nx >= m or ny < 0 or ny >= n:
continue
if volcano_visit_time[nx][ny] <= nt:
continue
volcano_visit_time[nx][ny] = nt
q.append((nx, ny, nt))
def bfs(x, y):
ans = (graph[x][y], 0)
q = deque([(x, y, 0)])
js_visited[x][y] = True
while q:
cx, cy, ct = q.popleft()
nx = cx + dx[i]
ny = cy + dy[i]
nt = ct + 1
if nx < 0 or nx >= m or ny < 0 or ny >= n:
continue
if js_visited[nx][ny]:
continue
if volcano_visit_time[nx][ny] <= nt: …
```
=> [BOJ] 16569: 화산쇄설류

dydwo0740/baekjoon/7983.java
https://www.acmicpc.net/problem/7983
마감기간을 역순으로 정렬을 합니다. 그리고 최대로 늦게 시작할 수 있게 초기화를 시키는데 만약 이전에 끝낸 기한이 그 다음 기간보다 뒤에 있을 경우에는 해당 작업을 반복하고 만약 마감기간보다 앞에 있을때는 그 시점에서 소요기간을 빼줍니다.
``` java
PriorityQueue<int[]> pq = new PriorityQueue<>(new Comparator<int[]>() {
@Override
public int compare(int[] o1, int[] o2) {
return o2[1] - o1[1];
}
});
int d = …
```
=>  [BOJ] 7983: 내일 할거야

qsunki/baekjoon/9944.py
https://www.acmicpc.net/problem/9944
백트래킹
``` python java c++
import sys
def back(x, y, d, move_cnt, visit_cnt):
global ans
if visit_cnt == blank_cnt:
ans = min(ans, move_cnt)
return
nx = x + dx[d]
ny = y + dy[d]
cnt = 0
while 0 <= nx < n and 0 <= ny < m and graph[nx][ny] == 0:
cnt += 1
nx = nx + dx[d]
ny = ny + dy[d]
if visit_cnt + cnt == blank_cnt:
ans = min(ans, move_cnt)
return
if i % 2 == d % 2:
continue
nx = x + dx[d] * cnt + dx[i]
ny = y + dy[d] * cnt + dy[i]
if nx < 0 or nx >= n or ny < 0 or ny >= m or graph[nx][ny] == 1:
continue
for j in range(cnt + 1):
graph[x + dx[d] * j][y + dy[d] * j] = 1
back(nx, ny, i, move_cnt + 1, visit_cnt + cnt + 1)
for j in range(cnt + 1):
graph[x + dx[d] * j][y + dy[d] * j] = 0
sys.setrecursionlimit(10 ** 8)
t = 0
while True:
t += …
```
=> [BOJ] 9944: NxM 보드 완주하기

kwyoohae/baekjoon/14925.java, kwyoohae/baekjoon/17305.java, kwyoohae/baekjoon/2655.java, kwyoohae/baekjoon/28291.java, kwyoohae/baekjoon/4650.java, kwyoohae/baekjoon/7983.java
[[BOJ] 17305: 사탕 배달](https://www.acmicpc.net/problem/17305)
처음에는 설탕 배달이겠거니했는데 읽어보니 그리디 누적합 문제였습니다 
첫번째는, 사실 최대한 5g짜리 사탕을 많이 채우고 5g사탕을 하나씩 빼면서 최대의 3g 사탕을 넣으면서 모든 수를 구했지만
이러면 3g사탕이 2개가 들어갈수도있고 구현이 살짝더 복잡해져 3g사탕을 최대한 많이 넣고, 하나씩 빼면서 5g사탕을 최대한 많이 넣는 방식으로 했습니다 
우선 3g, 5g에 대해서 정렬을 하고, 이후 누적합을 구합니다 
index는 사탕을 얼마나 넣었는지를 나타내기때문에, 해당 인덱스를 잘사용해서 3g과 5g을 얼마나넣었는지 누적합 배열을 이용해서 풀이를합니다 
특히 중요한것은 당도는 10의 9승이므로 int가 들어가지만 누적합이기 때문에.. long을 써야합니다... 이부분에서 몇번틀려서 시간이 더걸렸습니다
``` python java c++
import java.util.Collections;
public static void main(String[] args) throws Exception {
BufferedReader br = new BufferedReader(new …
```
=> [BOJ] 17305: 사탕 배달

dydwo0740/baekjoon/28325.java
https://www.acmicpc.net/problem/28325
우선 개미의 쪽방은 있다면 한개 이상이므로 모든 쪽방은 다 채우고 시작합니다. 이때 쪽방이 채워졌다면.  방은 채울 수 없습니다. 이를 고려하여 순차적으로 방에 대해서 넣을 수 있는 방인지 아닌지를 판단합니다. 양쪽방이 비어져있다면 무조건 방에 개미를 넣습니다. 이때 시작점은 0번째부터 (단, 쪽방이 >0 인 값이 있다면, 해당 방 다음 방 부터 시작합니다.)
``` java
boolean[] visited = new boolean[N];
int[] empty = new int[N]; // 만약 절대 안들어가는 노드면 -1
long ans = 0;
int start = -1;
for (int i = 0; i < N; i++) …
```
=>  [BOJ] 28325: 호숫가의 개미굴

kwyoohae/baekjoon/14925.java, kwyoohae/baekjoon/17305.java, kwyoohae/baekjoon/2655.java, kwyoohae/baekjoon/28291.java, kwyoohae/baekjoon/28325.java, kwyoohae/baekjoon/4650.java, kwyoohae/baekjoon/7983.java
[[BOJ] 28325: 호숫가의 개미굴](https://www.acmicpc.net/problem/28325)
원형이라는 점이 중요한 문제입니다. 
원형으로 돌기 때문에 결국 시작점을 방문했는지, 안했는지에 대해서 2번을 비교해야합니다 
해당 문제랑 비슷하게 원형이라는 특이점이 있다면 잘 쓰일것 같아서 기억해두면 좋을것 같습니다 
또한, C가 10의 12승이기 때문에 꼭 long으로... 해야합니다 또 까먹고 돌리다가 틀렸습니다. 
아이디어 찾는데 조금 고민이 되었습니다 
``` python java c++
public static void main(String[] args) throws Exception{
int N = Integer.parseInt(br.readLine());
long []ants = new long[N];
String []input = br.readLine().split(" ");
ants[i] = Long.parseLong(input[i]);
}
boolean []visited = new boolean[N];
long answer1 = ants[0];
if (ants[0] == 0) {
visited[0] = true;
answer1 = 1;
} …
```
=> [BOJ] 28325: 호숫가의 개미굴

dydwo0740/baekjoon/18430.java
https://www.acmicpc.net/problem/18430
dfs를 활용하여 해결했습니다. 우선 현재 (x, y)를 부메랑의 중심이라고 생각하고 부메랑을 만들 수 있는 좌표에 대해서 반복문을 돌려주었습니다. 
``` java
static boolean flag = false;
static int ans = 0;
static int N;
static int M;
static int[][] col = {{-1, 0}, {-1, 0}, {0, 1}, {0, 1}};
static int[][] row = {{0, 1}, {0, -1}, {-1, 0}, {1, 0}};
M = Integer.parseInt(st.nextToken());
int[][] board = new int[N][M];
st = new …
```
=> [BOJ] 18430: 무기공학

qsunki/baekjoon/18430.py
https://www.acmicpc.net/problem/18430
현재 칸이 중심이 될 때의 4가지 경우와 중심이 아닐 때 총 5가지 경우를 고려하는 백트래킹
``` python java c++
import sys
def back(x, y, sum_):
if y == m:
x += 1
y = 0
if x == n:
global ans
ans = max(ans, sum_)
return
if not visited[x][y]:
nx = x + dx[i]
ny = y + dy[i]
if nx < 0 or nx >= n or ny < 0 or ny >= m:
continue
if visited[x][ny] or visited[nx][y]:
continue
visited[x][y] = True
visited[x][ny] = True
visited[nx][y] = True
back(x, y + 1, sum_ + graph[x][y] * 2 + graph[x][ny] + graph[nx][y])
visited[x][y] = False
visited[x][ny] = False
visited[nx][y] = False
back(x, y + 1, sum_)
n, m = map(int, sys.stdin.readline().split())
graph = [list(map(int, sys.stdin.readline().split())) for _ in range(n)]
visited = [[False] * m for _ in range(n)]
dx = [1, 1, -1, -1]
dy = [1, …
```
=> [BOJ] 18430: 무기 공학

dydwo0740/baekjoon/28017.java
https://www.acmicpc.net/problem/28017
500^3 을 해도 시간초과가 나지 않기 때문에, 삼중 for 문을 활용해서 dp 방식으로 풀었습니다.
우선 같은 무기 번호를 사용하지 않는 누적합에서 최소를 구하고 해당 값을 계속 더해주는 식으로
설계를 했습니다.
``` java
int[][] dp = new int[N + 1][M];
for (int i = 1; i <= N; i++) {
for (int j = 0; j < M; j++) {
int min = Integer.MAX_VALUE;
for (int k = 0; k < M; k++) {
if (j == k) {
continue;
}
min …
```
=> [BOJ] 28017: 게임을 클리어하자

dydwo0740/baekjoon/12908.java
https://www.acmicpc.net/problem/12908
처음에는 아무 생각없이 bfs를 통해 구현했지만 실패했습니다.
그래서 완전탐색으로 모든 텔레포트 경우를 저장하고 텔레포트를 0번, 1번,....6번 모두 이용했을 경우에 대해
모두 생각했습니다.
이때 6가지가 나오는 이유는 3가지 텔레포트의 경우 2번의 이동이 가능하기 때문입니다.
``` java
static class Location{
int sx;
int sy;
int ex;
int ey;
public Location(int sx, int sy, int ex, int ey) {
this.sx = sx;
this.sy = sy;
this.ex = ex;
this.ey = ey;
}
}
static int startX;
static int startY;
static int endX;
static int endY;
static long min = Long.MAX_VALUE;
static List<Location>[] list;
StringTokenizer st = new …
```
=> [BOJ] 12908: 텔레포트 3

dydwo0740/baekjoon/2313.java
https://www.acmicpc.net/problem/2313
누적합을 활용해서 모든 경우의 수에 대해서 탐색을 했습니다.
이때 음수도 있기 때문에 초기값을 Integer.MIN_VALUE로 초기화 해줘야 합니다.
```java
static List<Integer>[] sum;
static int[] length;
static int[][] answer;
static long ans = 0;
sum = new ArrayList[N];
sum[i] = new ArrayList<>();
}
length = new int[N];
answer = new int[N][2];
int size …
```
=> [BOJ] 2313: 보석 구매하기

dydwo0740/baekjoon/23740.java
https://www.acmicpc.net/problem/23740
start 와 end를 오름차순 정렬을 한 후 영역안에 들어온다면 계속 확장을 하고, 그렇지 않다면 이전 영역을 저장하고 다시 시작하는 방식으로 해결합니다.
``` java
static class Bus{
long start;
long end;
long cost;
public Bus(long start, long end, long cost) {
this.start = start;
this.end = end;
this.cost = cost;
}
}
List<Bus> list = new ArrayList<>();
List<Bus> res = new ArrayList<>(); …
```
=> [BOJ] 23740: 버스 노선 개편하기

.github/get_problem/.gitignore, .github/get_problem/main.js, .github/get_problem/package.json, .github/workflows/get_problem.yml
랜덤 알고리즘을 Github Issues에 등록하는 workflow입니다.
=> 램덤알고리즘 workflow

.github/get_problem/main.js, .github/workflows/get_problem.yml
=> 램덤 알고리즘 웹훅 워크플로우에 포함

.github/get_problem/main.js
=> 랜덤 알고리즘 리팩토링

.github/get_problem/.gitignore, .github/get_problem/package-lock.json, .github/workflows/get_problem.yml
Add cache at 'Get problem and GitHub Issue' workflow
=> Add cache at 'Get problem and GitHub Issue' workflow

qsunki/baekjoon/17299.py
https://www.acmicpc.net/problem/17299
오큰수문제와 비슷한 문제 https://www.acmicpc.net/problem/17298
빈도수를 센 후 수열을 역순으로 순회하면서 현재 빈도 수가 스택의 빈도 수보다 크거나 같을 때 스택의 수를 꺼낸다.
현재 빈도 수가 더 작다면 스택의 최상위에 있는 수가 오등큰수
``` python java c++
import sys
from collections import defaultdict
A = list(map(int, sys.stdin.readline().split()))
F = defaultdict(int)
stack = []
result = [-1] * n
for x in A:
F[x] += 1
for i in range(n - 1, -1, -1):
while stack and F[A[i]] >= F[stack[-1]]:
stack.pop()
if stack:
result[i] = stack[-1]
stack.append(A[i])
print(*result)
```
=> [BOJ] 17299: 오등큰수

qsunki/baekjoon/12834.py
https://www.acmicpc.net/problem/12834
KIST와 씨알푸드에서 각 회원 집까지 최단거리 구하기(다익스트라)
``` python java c++
import sys
from heapq import *
def dijkstra(x):
distance = [INF] * (V + 1)
q = [(0, x)]
distance[x] = 0
while q:
dist, u = heappop(q)
if distance[u] < dist:
continue
for v, w in graph[u]:
cost = dist + w
if cost >= distance[v]:
continue
distance[v] = cost
heappush(q, (cost, v))
return distance
INF = float('inf')
N, V, E = map(int, sys.stdin.readline().split())
A, B = map(int, sys.stdin.readline().split())
members = map(int, sys.stdin.readline().split())
graph = [[] for _ in range(V + 1)]
for _ in range(E):
u, v, w = map(int, sys.stdin.readline().split())
graph[u].append([v, w])
graph[v].append([u, w])
d1 = dijkstra(A)
d2 = dijkstra(B)
ans = 0
for member in members:
if d1[member] == INF: …
```
=> [BOJ] 12834: 주간 미팅

dydwo0740/baekjoon/20440.java
https://www.acmicpc.net/problem/20440
우선순위 큐를 활용해서 최대로 많은 모기가 있던 경우를 찾으려고 합니다.
``` java
List<int[]> list = new ArrayList<>();
int start = Integer.parseInt(st.nextToken());
int end = Integer.parseInt(st.nextToken());
list.add(new int[]{start, end});
}
list.sort(new Comparator<int[]>() {
@Override
public int compare(int[] o1, int[] o2) {
if (o1[0] == o2[0]) { …
```
=> [BOJ] 20440:🎵니가 싫어 싫어 너무 싫어 싫어 오지 마 내게 찝쩍대지마🎵 - 1

dydwo0740/baekjoon/2140.java
https://www.acmicpc.net/problem/2140
숫자가 적혀있는 칸에서 대각선을 포함한 모든 방향을 탐색하며 지뢰를 넣습니다.
이때 안쪽에는 무조건 지뢰를 설치할 수 있음을 인지합니다.
``` java
static int[] row = {-1, -1, -1, 0, 0, 1, 1, 1};
static int[] col = {-1, 0, 1, -1, 1, -1, 0, 1};
char[][] board = new char[N][N];
String str = st.nextToken();
for (int j = 0; j < N; j++) {
board[i][j] = str.charAt(j);
}
}
for (int i = 0; i …
```
=> [BOJ] 2140: 지뢰찾기

dydwo0740/baekjoon/5502.java
https://www.acmicpc.net/problem/5502
처음에는 아무 생각없이 bfs를 돌렸더니 메모리 초과가 났습니다. 그래서 LCS를 사용해서 해결했습니다.
일단 문자열이 주어지면 해당 문자열의 역순을 다른 변수에 저장하고 LCS를 통해 최대 연속 닮음을 구하고
총 길이에서 빼주면 됩니다.
``` java
static class Node{
String str;
int cnt;
public Node(String str, int cnt) {
this.str = str;
this.cnt = cnt;
}
}
StringBuilder sb = new StringBuilder();
sb.append(st.nextToken());
StringBuilder reverse = new …
```
=> [BOJ] 5502: 팰린드롬

dydwo0740/baekjoon/1132.java
https://www.acmicpc.net/problem/1132
ABC 일때 각각의 알파벳에 가중치를 두고 가중치가 큰 순서대로 9부터 1씩 감소하는 숫자를 할당합니다.
여기서 발생할 수 있는 예외 사항은 앞자리의 숫자가 0이 될때입니다. 
해당 경우는 10가지 숫자가 나올 경우이므로 해당 예외 케이스에 에러처리를 합니다.
이때 가장 가중치가 낮은 순서부터 앞자리에 나오지 않은 숫자를 찾으면 됩니다.
```java
static class Alpha {
char ch;
long weight;
public Alpha(char ch, long weight) {
this.ch = ch;
this.weight = weight;
}
}
long[] alpha = new long[26];
String[] s = new String[N];
Set<Character> first …
```
=> [BOJ] 1132: 합

dydwo0740/baekjoon/16437.java
https://www.acmicpc.net/problem/16437
후위순위를 통해 건너올 수 있는 양의 숫자를 누적해서 반환합니다.
후위순위와 그래프 탐색시에 시간복잡도를 계산하는 연습이 필요할 것 같습니다.
``` java
long count;
public Node(long count) {
this.count = count;
}
}
static Node[] nodes;
List<Integer>[] g = new ArrayList[N + 1];
nodes = new Node[N + 1];
nodes[1] = new Node(0);
for (int i = 1; i <= N; i++) {
g[i] = new ArrayList<>();
}
for (int i = 2; i <= N; i++) {
st = new …
```
=> [BOJ] 16437: 양 구출 작전

dydwo0740/baekjoon/30105.java
https://www.acmicpc.net/problem/30105
단순히 idx 0에 위치한 원소와 그 후순위 원소들의 차이를 저장하고,
Set 을 활용해서 모든 값들의 제거가 가능한지에 대한 판별을 진행했습니다.
```java
int[] seq = new int[N];
Set<Integer> origin = new HashSet<>();
seq[i] = Integer.parseInt(st.nextToken());
origin.add(seq[i]);
}
int[] diff = new int[N - 1];
for (int i = 1; i < N; i++) {
diff[i - 1] = seq[i] - seq[0];
} …
```
=> [BOJ] 30105: 아즈버의 이빨 자국

dydwo0740/baekjoon/21941.java
https://www.acmicpc.net/problem/21941
dp를 활용해서 해결했습니다. 우선 문자열의 길이가 1000이므로 시간초과는 날 것 같지 않았기에 문자열의 길이를 0부터 N 까지 증가시키면서 하면 될 것 같다고 생각했습니다.
그리고 이때 문자열의 길이보다 작은 점수가 있다면 Map 에 포함하지 않았습니다. 만약 3까지의 거리에 도달했다고 하면 dp[0] 과 그 이후의 문자열의 최대 점수를 비교 dp[1] 과 그 이후의 문자열의 최대 점수를 비교하는 형태로 구현했습니다.
``` java
static Map<String, Integer> map = new HashMap<>();
String str = st.nextToken();
int len = str.length();
int[] dp = new int[len];
int N = …
```
=> [BOJ] 21941: 문자열 제거

qsunki/baekjoon/15924.cpp
https://www.acmicpc.net/problem/15924
(n, m)부터 (1, 1)까지 순회하면서 문자에 따라 가짓수 저장
``` c++
#include <iostream>
#include <algorithm>
#include <queue>
#include <vector>
char graph[3001][3001];
int num_paths[3001][3001];
int main() {
ios_base::sync_with_stdio(false);
cin.tie(nullptr);
int n, m;
cin >> n >> m;
int total_paths = 0;
for (int i = 0; i < n; ++i) {
for (int j = 0; j < m; ++j) {
cin >> graph[i][j];
}
}
for (int i = n - 1; i >= 0; --i) {
for (int j = m - 1; j >= 0; --j) {
if (graph[i][j] == 'X') {
num_paths[i][j] = 1;
} else if (graph[i][j] == 'E') {
num_paths[i][j] = num_paths[i][j + 1];
} else if (graph[i][j] == 'B') {
num_paths[i][j] = num_paths[i][j + 1] + num_paths[i + 1][j];
} else if (graph[i][j] == 'S') { …
```
=> [BOJ] 15924: 욱제는 사과팬이야!!

dydwo0740/baekjoon/14395.java
https://www.acmicpc.net/problem/14395
bfs 를 활용하여 해결했습니다. - 와 / 연산을 생각해보면 항상 0이 되거나 1이 되기 때문에 + 와 * 연산만 고려해주면 됩니다. 여기서 - 연산은 s, t 가 1부터 시작되기 때문에 아예 고려를 하지 않았고, 2번째부터 1과 / 를 클래스에 저장하여 로직을 실행했습니다. 방문처리같은 경우에는 배열의 한계 이상을 저장해야 하기 때문에, Set을 활용했습니다.
``` java
static long N;
static long M;
static class Step {
long num;
String str = "";
public Step(long num, String str) {
this.num = num;
this.str = str;
}
}
N = Long.parseLong(st.nextToken());
M = Long.parseLong(st.nextToken()); …
```
=> [BOJ] 14395: 4연산

qsunki/baekjoon/4095.cpp
https://www.acmicpc.net/problem/4095
``` python java c++
#include <iostream>
#include <algorithm>
#include <cstring>
int matrix[1001][1001];
int main() {
ios_base::sync_with_stdio(false);
cin.tie(nullptr);
int n, m;
while (true) {
cin >> n >> m;
if (n == 0 && m == 0) break;
int max_square = 0;
memset(matrix, 0, sizeof(matrix));
for (int i = 1; i <= n; ++i) {
for (int j = 1; j <= m; ++j) {
cin >> matrix[i][j];
if (matrix[i][j] == 0) continue;
int tmp = min({matrix[i - 1][j - 1], matrix[i][j - 1], matrix[i - 1][j]});
matrix[i][j] = tmp + 1;
max_square = max(max_square, matrix[i][j]);
}
}
cout << max_square << '\n';
}
return 0;
}
```
=> [BOJ] 4095:최대 정사각형

dydwo0740/baekjoon/9082.java
https://www.acmicpc.net/problem/9082
각각의 index의 숫자에 대해서 0이 아니라면 답을 1씩증가하고 접하는 모든 노드의 값을 빼주는 식으로 설계 했습니다.
``` java
static int[] col = { 1, 0, -1 };
for (int test = 1; test <= T; test++) {
int[] …
```
=> [BOJ] 9082: 지뢰찾기

dydwo0740/baekjoon/3806.java
https://www.acmicpc.net/problem/3806
첫번째 문자열에서 두번째 경우에 될 수 없는 경우에 -1을 반환합니다. 그 외의 경우에는 0을 1로 그리고 ? 에 적절한 문자로 변환을 합니다. 그리고 자리 교환의 경우에는 횟수/2 을 더합니다.
``` java
public class Main{
for (int test = 1; test <= T; test++) {
st = new …
```
=> [BOJ] 3806: S를 T로

dydwo0740/baekjoon/23883.java
https://www.acmicpc.net/problem/23883
map을 활용해서 해결했습니다. 선택정렬의 의사코드를 자세히 읽어보지 않아서 실패를 많이 했습니다.
정렬된 배열을 하나 저장하고, 정렬 전 배열의 원소값과 idx를 map에 담아두고 swap을 진행하면서 해결했습니다.
``` java
import java.util.PriorityQueue;
static Map<Integer, Integer> map = new HashMap<>();
StringTokenizer st = new …
```
=> [BOJ] 23883: 알고리즘 수업 - 선택 정렬 3

dydwo0740/baekjoon/23742.java
https://www.acmicpc.net/problem/23742
처음에는 단순하게 음수값의 경우에는 각자 하나의 그룹으로 묶고, 양수는 모두 같은 그룹으로 나누었더니 틀렸습니다. 
생각해보니 "만약 마이너스가 아주 작다면 오히려 같은 그룹에 묶어서 배수의 효과를 봅니다." 를 고려하지 않았습니다.
그래서 우선 모두다 하나의 그룹으로 묶은 값을 저장하고 만약 오름차순 정렬시 맨앞 숫자가 음수라면 음수를 하나씩 분리하며 최댓값으로 초기화를 했습니다.
``` java
import java.util.PriorityQueue;
static Map<Integer, Integer> map = new HashMap<>();
BufferedWriter bw = new …
```
=> [BOJ] 23742: Player-based Team Distribution

dydwo0740/baekjoon/20209.java
https://www.acmicpc.net/problem/20209
bfs를 통해 모든 경우의 수를 체크 합니다. 이때 각 스위치의 상태를 String으로 변환하여 Set을 활용하여 방문처리를 해주었습니다.
``` java
import java.util.HashSet;
import java.util.LinkedList;
import java.util.Queue;
import java.util.Set;
static Map<Integer, int[]> map = new HashMap<>();
static Set<String> visited = new HashSet<>();
BufferedWriter bw = new BufferedWriter(new …
```
=> [BOJ] 20209: 스트레이트 스위치 게임

dydwo0740/baekjoon/28270.java
https://www.acmicpc.net/problem/28270
동일한 부모를 가졌다고 판단하는 근거는 값의 증가입니다. 해당 경우에는 index의 count값을 1로 초기화
처음에는 해당 index보다 큰 값들 모두 초기화 하려고 했습니다. (TLE) 그래서 하나만 초기화를 진행했습니다. 어차피 아래의 노드로 탐색하는 방향은 일정
``` java
// 형제 노드란 부모가 같습니다. 선형적으로 선정
// 형제 노드!
int[] seq = new int[N];
int[] count = new int[1000001];
int[] answer = new int[N];
Arrays.fill(count, 1);
int max = 1;
for(int i=0;i<N;i++) {
seq[i] = …
```
=> [BOJ] 28270: Marked-Numbered

dydwo0740/baekjoon/15482.java
https://www.acmicpc.net/problem/15482
단순한 LCS
``` java
String std = st.nextToken();
String comp = st.nextToken();
int N = std.length();
int M = comp.length();
int[][] dp = new int[N+1][M+1];
for(int i=1;i<=N;i++) {
for(int j=1;j<=M;j++) {
if(std.charAt(i - 1) == comp.charAt(j - 1)) {
dp[i][j] = dp[i-1][j-1] + 1;
continue;
} 
dp[i][j] = Math.max(dp[i-1][j], dp[i][j-1]);
}
}
bw.write(dp[N][M]+"\n");
bw.flush();
br.close(); …
```
=> [BOJ] 15482: 한글 LCS

dydwo0740/baekjoon/10993.java
https://www.acmicpc.net/problem/10993
우선 board의 가로와 세로의 길이를 점화식을 활용하여 구했습니다.
그리고 규칙에 따라 하나씩 채우는 단순 구현 형식을 채택했습니다.
``` java
static int[] height = new int[11];
static int[] width = new int[11];
int idx = Integer.parseInt(st.nextToken());
int origin = idx;
height[1] = 1;
width[1] = 1;
for (int i = 2; i <= 10; i++) {
height[i] = (height[i - 1] * 2) + 1;
width[i] = (width[i - 1] + 2) * 2 - 1;
}
int N = height[idx];
int M = width[idx];
int[][] board = new int[N][M];
if (idx …
```
=> [BOJ] 10993: 별 찍기 - 18

dydwo0740/baekjoon/16169.java
https://www.acmicpc.net/problem/16169
dp를 활용해서 해결했습니다. 우선 각 레벨의 시스템을 idx 로 설정하고 List에 저장을 했습니다.
그리고 이중 for문을 돌면서 각각의 시스템에서 이전 값으로부터 실행되서 전송을 할 수 있는 시간을 초기화 했습니다.
좌표가 이미 압축된 형태로 주어졌기 때문에 풀기 편했습니다.
``` java
int weight;
int index;
Node(int weight, int index) {
this.weight = weight;
this.index = index;
}
}
List<Node>[] list = new ArrayList[101];
for (int i = 1; i <= 100; i++) {
list[i] = new ArrayList<>();
} …
```
=> [BOJ] 16169: 수행 시간

dydwo0740/baekjoon/30805.java
https://www.acmicpc.net/problem/30805
우선 각각의 입력값을 value와 index를 동시에 저장을 했습니다. 사전순 정렬이기 때문에, value 값이 큰 순이 마지막에 오기 때문에 value의 역순 그리고 value가 같다면 index의 오름차순으로 정렬을 합니다. ( 만약 동일한 값이 나왔어도 index가 작다면 한번 더 사용가능) 그리고 같다면 각각의 prevA, prevB의 위치를 초기화하면서 Queue의 원소를 삭제하면서 해결합니다.
```java
int value;
int index;
Node(int value, int index) {
this.value = value;
this.index = index;
}
}
/*
* 우선 각각 역으로 sorting index도 같이 저장합니다. 만약 value 가 같다면 ..? 먼저 오는 것으로
*/ …
```
=> [BOJ] 30805: 사전 순 최대 공통 부분 수열

qsunki/baekjoon/18231.java
https://www.acmicpc.net/problem/18231
도시가 파괴되었는지를 boolean배열 destroyed에 저장하고
파괴된 도시를 순회하면서 이웃도시가 파괴된 도시에 포함되는지를 확인하고
포함된다면 visited에 방문체크를 하고 정답리스트에 이 파괴된 도시를 추가한다.
destroyed와 visited가 같다면 지도와 같은 모양을 만들 수 있으므로 정답리스트를 출력
``` java
class Main {
StringBuilder sb = new StringBuilder();
String[] line = br.readLine().split(" ");
int n = Integer.parseInt(line[0]);
int m = Integer.parseInt(line[1]);
Graph graph = new Graph(n + 1);
for (int i = 0; i < m; ++i) {
line = br.readLine().split(" ");
int u = …
```
=> [BOJ] 18231: 파괴된 도시

qsunki/baekjoon/31063.java
https://www.acmicpc.net/problem/31063
사탕수수의 시작높이를 0으로 초기화하고
각 사탕수수에 대해서 모든 소들에 대해 사탕수수의 양과 시작높이, 소의 키를 조건에 맞추어 업데이트 해주면 된다.
사탕수수를 다먹었을 때는 다른 소들에 대해서 고려하지 않도록하여 시간을 줄인다.
``` java
String[] line;
line = br.readLine().split(" ");
int n = Integer.parseInt(line[0]);
int m = Integer.parseInt(line[1]);
line = br.readLine().split(" ");
long[] cows = new long[n];
for (int i = 0; i < n; i++) {
cows[i] = Long.parseLong(line[i]);
}
line = br.readLine().split(" ");
outer:
for (int i = 0; i < m; i++) {
long amount = Integer.parseInt(line[i]);
long height = 0L; …
```
=> [BOJ] 31063: Candy Cane Feast

dydwo0740/baekjoon/28359.java
https://www.acmicpc.net/problem/28359
처음에 생각했던 부분은 오름차순으로 정렬하고 배열을 바꿔주는 방식이였습니다. 하지만 그렇게 코드를 설계하면 문제의 예시에서 볼 수 있듯이 1 2 2 3 오름차순 합: 8 을 구해주는 것은 되지만 내림차순 합의 최대가 4인데 3으로 초기화를 시키는 오류가 있었습니다. 그래서 map을 활용하여 숫자의 갯수를 따로 저장하고 중복이 없는 배열의 형태로 저장했습니다.
그렇게 되면 1 2 3 -> 1 3 2 -> 3 2 1 이렇게 배열을 변환하면서 오름차순, 내림차순을 각각 구할 수 있었습니다.
만약 1 2 2 3 -> 1 2 3 2 -> 1 3 2 2 -> 3 2 2 1이렇게 된다 하더라도 성립이 가능합니다.
```java
import java.util.stream.*;
static Map<Integer, Integer> map = new HashMap<>();
int N = …
```
=> [BOJ] 28359: 수열의 가치

qsunki/baekjoon/25682.java
https://www.acmicpc.net/problem/25682
체스판은 흰색으로 시작하거나 검은색으로 시작한다. 두 경우에 대해서 2차원배열에 현재 보드와 다른 부분을 1로 같은 부분을 0으로 저장한다.
그후에 누적합을 구하면 임의의 범위에 대해서 상수시간에 다른 부분이 몇 개인지 파악할 수 있다.
``` java
String[] line = br.readLine().split(" ");
int n = Integer.parseInt(line[0]);
int m = Integer.parseInt(line[1]);
int k = Integer.parseInt(line[2]);
int[][] boardDiffW = new int[n + 1][m + 1];
int[][] boardDiffB = new int[n + 1][m + 1];
int[][] pSumW = new int[n + 1][m + 1];
int[][] pSumB = new int[n + 1][m + 1];
for (int i = 1; i <= n; ++i) {
char[] chars = …
```
=> [BOJ] 25682: 체스판 다시 칠하기 2

dydwo0740/baekjoon/2513.java
https://www.acmicpc.net/problem/2513
그냥 단순 구현입니다. 최대한 멀리 있는 거리에 대해서 갔다가 최대한 많은 사람들을 태우고 오는 작업을 반복합니다.
```java
import java.util.stream.*;
int K = Integer.parseInt(st.nextToken());
int S = Integer.parseInt(st.nextToken());
PriorityQueue<int[]> left = new PriorityQueue<>((o1, o2) -> o1[0] - o2[0]);
PriorityQueue<int[]> right = new PriorityQueue<>((o1, o2) -> o2[0] - o1[0]);
for(int i=0;i<N;i++) {
st = new …
```
=> [BOJ] 2513: 통학버스

qsunki/baekjoon/24727.java
https://www.acmicpc.net/problem/24727
두 공간이 최대한 떨어지도록 대각으로 배치하면 된다. 꼭짓점에서 지그재그로 순회하는 것에 애를 먹었다.
``` java
int n = Integer.parseInt(br.readLine());
int[][] space = new int[n][n];
split = br.readLine().split(" ");
int c = Integer.parseInt(split[0]);
int e = Integer.parseInt(split[1]);
if (n * n < c + e) {
System.out.println(-1);
return;
}
int cycle = 0;
int fillCnt = 0;
int cCnt = 0;
int xStart = 0;
int yStart = 0;
outer:
while (cCnt < c) {
for (int j = …
```
=> [BOJ] 24727: 인지융~

qsunki/baekjoon/20033.java
https://www.acmicpc.net/problem/20033
한 변이 n인 정사각형이 존재한다면 한 변이 1~n - 1인 정사각형이 존재한다. 가장 큰 정사각형을 찾기 위해 이분탐색을 활용한다. 이분탐색에 O(logN) 정사각형 존재 여부 판단에 O(N)이 걸리므로 총 시간복잡도는 O(NlogN)
``` java
static int[] nums;
static int n;
n = Integer.parseInt(br.readLine());
split = br.readLine().split(" ");
nums = new int[n];
for (int i = 0; i < n; ++i) {
nums[i] = Integer.parseInt(split[i]);
}
int low = 1;
int high = n;
while (low <= high) {
int mid = (low + high) >>> 1;
if …
```
=> [BOJ] 20033: Square, Not Rectangle

qsunki/baekjoon/17953.java
https://www.acmicpc.net/problem/17953
k일에 x디저트를 먹었을 때 최대 만족도를 dp[k][x]에 저장한다.
k일의 x디저트 만족도를 nums[k][x]라고 하면
dp[k][x] = MAX( dp[k - 1][x가 아닌 디저트] + nums[k][x], dp[k - 1][x] + nums[k][x] / 2 )
``` java
static String[][] splits;
split = br.readLine().split(" ");
int n = Integer.parseInt(split[0]);
int m = Integer.parseInt(split[1]);
int[][] dp = new int[n][m];
int[][] nums = new int[n][m];
splits = new String[m][];
for (int i = 0; i < m; i++) {
splits[i] …
```
=> [BOJ] 17953: 디저트

dydwo0740/baekjoon/5931.java
https://www.acmicpc.net/problem/5931
각각의 영역의 좌표를 모두 저장하고 이중 for문으로 비교하여 최단 거리를 도출합니다.
```java
static int N;
static int M;
M = Integer.parseInt(st.nextToken());
List<int[]> partA = new ArrayList<>();
List<int[]> partB = new ArrayList<>();
char[][] board = new char[N][M];
String str = …
```
=> [BOJ] 5931: Cow Beauty Pageant

dydwo0740/baekjoon/16765.java
https://www.acmicpc.net/problem/16765
dp를 활용했습니다. 우선 해당 index를 기준으로 index 만 포함, 그 이전 index 포함 ,,,,,, 그리고 K 전까지 간다고 했을때 최대가 되는 값을 저장합니다.
```java
int K = Integer.parseInt(st.nextToken());
int[] seq = new int[N + 1];
for(int i=1;i<=N;i++) {
seq[i] = Integer.parseInt(st.nextToken());
}
int[] dp = new int[N + 1];
dp[1] = seq[1];
if(N >= 2) {
dp[2] = Math.max(seq[1], seq[2]) * 2;
}
for(int …
```
=> [BOJ] 16765: Teamwork

qsunki/baekjoon/15551.java
https://www.acmicpc.net/problem/15551
자바 문자열 해시코드 구현을 보면 길이가 n인 문자열의 해시코드는 0부터 n - 1까지의 부분문자열의 해시코드에 31배를 하고 n번째 문자의 아스키코드를 더하여 구한다.
길이가 1인 문자열의 해시코드는 문자의 아스키코드 값이 되고
길이가 2인 문자열의 해시코드는 첫번째 문자의 해시코드에 31배를 하고 두번째 문자의 아스키코드값을 더하는데
해시코드가 같으려면 두번째 문자의 아스키코드값이 첫번째문자의 아스키코드값의 차이의 31배 차이가 나면 두 문자열의 해시코드가 같아진다.
해시코드가 같은 길이가 2인 문자열을 구했으면 이후에는 두 문자열에 같은 문자열을 더하면 계속해서 해시코드가 같다.
``` java
int n = Integer.parseInt(br.readLine());
StringBuilder a = new …
```
=> [BOJ] 15551: if 3

dydwo0740/baekjoon/16932.java
https://www.acmicpc.net/problem/16932
시간복잡도를 최소화 하기 위해서 bfs 와 union-find를 활용하여 해결했습니다. 처음에는 0인 부분들을 모두 1로 바꾸는 방법을 떠올렸는데 TLE 가 발생할 것 같아서 1의 덩어리들을 한번에 구하고 이때 union 과정을 진행합니다, 그리고 이중 for 문을 돌면서 0인 부분에 대해 4방향으로 1이 있다면 그 1의 좌표의 부모를 key로 하는 value를 더해주는 방식으로 해결했습니다.
```java
import java.util.stream.Collectors;
static int N;
static int M;
static int[][] board;
static int[] parent;
static Map<Integer, Integer> map = new HashMap<>(); // key 는 parent입니다. 그리고 value 는 넓이
static int[] row = {0, 0, 1, -1};
static int[] col = {1, -1, 0, 0}; …
```
=> [BOJ] 16932: 모양 만들기

qsunki/baekjoon/24463.java
https://www.acmicpc.net/problem/24463
시작점과 탈출점을 찾고 시작점에서 DFS를 수행한다. dfs반환값을 boolean으로하여 탈출 가능할 때 true를 반환하도록해서 탈출경로를 판단한다.
참고1)고립되어있는 길도 있다. 이 지점도 @로 채워야 하기때문에 처음에 .을 @로 초기화하고 탈출 가능할 때 .으로 바꿔줬다.
참고2)문제조건을 잘 보면 미로에 사이클이 없다. 처음엔 사이클이 있을 수 있지않을까해서 방문체크를 depth로 해주었는데 그럴필요가 없었다.
``` java
static int n;
static int m;
static char[][] miro;
static int startX;
static int startY;
static int endX;
static int endY;
static int[] dx = {0, 0, 1, -1};
static int[] dy = {1, -1, 0, 0};
static boolean[][] visited;
public static …
```
=> [BOJ] 24463: 미로

dydwo0740/baekjoon/27924.java
https://www.acmicpc.net/problem/27924
처음에는 BFS로 접근을 했는데, 시간초과도 발생했고, 최적의 조건으로 이동한다는 글을 읽지 못했습니다. 그래서 leaf노드에 대해서 최단 거리를 구한다음 윤아가 가장 빠르게 탈출할 수 있는 즉 거리가 가장 짧은 경우가 있는지를 찾아봅니다.
``` java
static int N;
static List<Integer>[] g;
static Set<Integer> leafNodes;
static int[][] dist;
g = new ArrayList[N + 1];
leafNodes = new HashSet<>();
dist = new int[3][N + 1];
for(int i=0;i<3;i++) {
Arrays.fill(dist[i], -1);
}
for(int i=1;i<=N;i++) {
g[i] = …
```
=> [BOJ] 27924: 윤이는 엄청난 것을 훔쳐갔습니다

dydwo0740/baekjoon/2746.java
https://www.acmicpc.net/problem/2746
index가 1부터 시작한다고 가정할때. [1, 2, 3, 4, 5, ..... N - 2, N - 1, N] 입니다. 이때 정렬이 된 상태라면 2개를 지웠을때 서브 집합이 가장 큰 수의 합이 되기 위해서는 가장 큰 수는 N (그 앞에 2가지 숫자를 제거), N - 1 ( N 과 그 앞에 1가지 숫자를 제거), N - 2(그 뒤 2가지 숫자를 제거) 의 경우가 있습니다. 그래서 for문을 돌면서 map에 숫자가 나오는 횟수를 각각 저장하고 경우의 수를 확인하였습니다. 
```java
import java.util.stream.Collectors;
static Map<Long, Long> map;
long[] seq = new long[N];
st = new …
```
=> [BOJ] 2746: 좋은 배열 만들기

qsunki/baekjoon/29618.java
https://www.acmicpc.net/problem/29618
처음에는 배열에 오른쪽 끝 정보를 저장하여 도화지를 왼쪽부터 탐색하며 색칠된 곳이라면 그 영역의 오른쪽 끝으로 가도록 했는데 이렇게 하면 길이가 짧은 영역이 매우 많을 때 탐색에 많은 시간이 걸린다.
만약에 두 영역이 배열 상에서 붙어 있다면 오른쪽 끝 정보를 가장 우측으로 업데이트하여 시간을 줄일 수 있다. 이를 위해 분리 집합을 사용하여 부모를 가장 우측 인덱스로 하여 해결하였다.
``` java
static StringTokenizer st;
int n = nextInt();
int q = nextInt();
DisjointSet set = new DisjointSet(n + 1);
int[] paint = new int[n + 1];
for (int i = 0; i < …
```
=> [BOJ] 29618: 미술 시간

qsunki/baekjoon/2370.java
https://www.acmicpc.net/problem/2370
벽의 길이가 10^8 이고 붙이는 포스터가 10^4개 이다. 포스터 갯수에 비해 벽의 길이가 너무 크기 때문에 좌표압축한 후에 입력 순서대로 배열을 업데이트 한 후에 보이는 포스터의 갯수를 세준다.
``` java
import java.util.Set;
import java.util.TreeSet;
static StringTokenizer st;
int n = nextInt();
int[][] inputCoordinates = new int[n][2];
Set<Integer> originalCoodinates = new TreeSet<>();
Map<Integer, Integer> …
```
=> [BOJ] 2370: 시장 선거 포스터

dydwo0740/baekjoon/19639.java
https://www.acmicpc.net/problem/19639
우선 적을 상대한 후 이진탐색을 통해서 찾을 수 있는 item 을 살펴보며 원복시킬 수 있는 모든 경우의 수를 담습니다.
가능한 만큼 원복을 시켰다고 할때 다시 적을 상대합니다.
``` java
import java.util.concurrent.*;
static class Node{
int index;
int value;
Node(int index, int value){
this.index = index;
this.value = value;
}
}
public static void main(String[] args) throws IOException{
int X = Integer.parseInt(st.nextToken());
int Y = Integer.parseInt(st.nextToken());
int origin = M;
List<Node> opposite = new ArrayList<>(); …
```
=> [BOJ] 19639: 배틀로얄

dydwo0740/baekjoon/9011.java
https://www.acmicpc.net/problem/9011
뒤에서 부터 시작을 해서 현재 저장된 index 와 내가 시작하는 N - 1이라는 index 의 차이값을 return 하는 식으로 구현을 합니다.
지금 현재 list 에 저장되어 있는 요소들중에 만족하게 설계를 해야하기 때문입니다.
``` java
package swexperttest;
public static void main(String[] args) throws Exception {
for(int test = 1;test<=T;test++) {
int[] seq = new int[N];
for(int i=0;i<N;i++) {
seq[i] = …
```
=> [BOJ] 9011: 순서

qsunki/baekjoon/2226.java
https://www.acmicpc.net/problem/2226
문제에서는 최초의 이진수가 1로 시작할 때 n번째 요소의 정보를 요구하고 있다. 이진수를 1에서 부터 전개해보면 이전 이진수와 비슷한 패턴이 나오는데 약간씩 다르다.
0으로 시작하는 이진수를 살펴보면 다른 부분은 0으로 시작하는 이진수에서 오는 것을 알 수 있다.
1로 시작하는 이진수
1: 1 -> 0
2: 01 -> 1
3: 1001 -> 1
4: 0110 1001 -> 3
5: 1001 0110 0110 1001 -> 5
6: 0110 1001 1001 0110 1001 0110 0110 1001 -> 11
0으로 시작하는 이진수
1: 0 -> 1
2: 10 -> 1
3: 0110 -> 2
4: 1001 0110 -> 3
5: 0110 1001 1001 0110 -> 6
6: 1001 0110 0110 1001 0110 1001 1001 0110 -> 11
n번째의 1로 시작하는 이진수는 n - 1번째의 0으로 시작하는 이진수 + n - 1번째의 1로 시작하는 이진수인데
n이 홀 수 일때는 n - 1번의 0으로 시작하는 이진수가 0으로 끝나면서 1로 시작하는 이진수가 0으로 시작하기 때문에 연속된 0의 갯수의 합에서 1을 빼준다.
값의 증가추세를 보면 약2배씩 늘어나는데 n이 최대 1000이므로 2^1000이 long범위를 넘어서므로 Biginteger클래스를 사용하여 큰 수를 처리한다.
``` java
import java.math.BigInteger;
public …
```
=> [BOJ] 2226: 이진수
